feat: JSON書式でログ出力する機能の追加
nablarch/nablarch-core-applog pull request #12
Opened 2021-03-08 01:19 UTC by shuji-k

・JSON書式でログ出力する為のJsonLogFormatterクラスの追加
・JsonLogObjectBuilderインターフェースの追加（シリアライズ対象のオブジェクトを生成するビルダーのインターフェース）
・FormatErrorSupportインターフェースの追加（フォーマットエラー出力を処理するインターフェース）
・JsonLogFormatterSupportクラスの追加（各種ログのJSON対応支援クラス）
・ApplicationSettingJsonLogFormatterクラスの追加（アプリケーション設定ログのJSON実装）
・FailureJsonLogFormatterクラスの追加（障害通知ログ、障害解析ログのJSON実装）
・PerformanceJsonLogFormatterクラスの追加（パフォーマンスログのJSON実装）
・CommitLoggerクラスの追加（コミットロガーのJSON実装）
・各種ログクラスの修正（継承して使用するための修正）

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/AppLogUtil.java
> +    public static final String getFilePath() {
`final` 修飾子は不要です。

静的メソッドに `final` をつけるのは、サブクラスでオーバーライドするのを防ぐときに利用できますが、このクラスはそもそも `final` でサブクラスが作れないので。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/ApplicationSettingJsonLogFormatter.java
> + * </pre>
`ApplicationSettingLogFormatter` の JSON と内容が重複していて二重管理になってしまうと思います。

基本的な説明は `@link` のドックレットで `ApplicationSettingLogFormatter` を参照させるようにして、差分（JSON で出力するというところ）だけ説明したほうがいいと思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/ApplicationSettingJsonLogFormatter.java
> +    private final JsonLogFormatterSupport support = new JsonLogFormatterSupport(PROPS_PREFIX);
private メンバーにも Javadoc の記載をお願いします。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> + * </pre>
説明が少し雑かなと思いました。

せめて、これらが何を表しているのか（出力される JSON ログに含まれるメンバーの名前とその説明であること）を文章で説明してあげたほうがいいと思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +        if (StringUtil.isNullOrEmpty(targetsStr)) targetsStr = DEFAULT_TARGETS;
括弧忘れ

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +     */
親クラスと Javadoc の内容が同じなので、記述不要かと思います。

オーバーライドしているメソッドの Javadoc が未記述の場合は、親のメソッドの Javadoc がそのまま出力されます。

他にも、親クラスのメソッドの Javadoc と同じことを書いているメソッドがあるので、一通り見直しをお願いします。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +import java.util.*;
import は `*` で省略せず、各クラスごとに明示的に import してください。

`*` を使っていると、そのクラスが具体的にどのクラスに依存しているのかを先頭の import 文から判断できなくなります。

IntelliJ が勝手に `*` にしてしまうとかであれば、以下のページなどを参考に設定をしてみてください。
https://blog.y-yuki.net/entry/2016/12/13/000000

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/FailureLogFormatter.java
> +import java.util.*;
import は省略せずに。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/JsonCommitLogger.java
> +        return "$JSON${\"commitCount\":" + count + '}';
接頭辞(`$JSON$`)は、デフォルトは `JsonLogFormatterSupport` の定数を参照しつつ、 Setter で変更できるようにしておいてください。
（`CommitLogger` はシステムリポジトリで管理するオブジェクトのはずだから、 Setter を用意しておけば大丈夫なはずです）

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +     * @param prefix 各種ログの設定内容から値と取得するのに使用するプロパティ名のプリフィックス、
> 値と取得する

値を取得する、のタイポ？

あと、文末が読点（、）になってます。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +     * @return 出力項目
> `@return 出力項目`

「出力項目のプロパティ名」ですね。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +        String messagePrefix = AppLogUtil.getProps().get(prefix + PROPS_STRUCTURED_MESSAGE_PREFIX);
`AppLogUtil.getProps()` を使って設定を読み込んでいる部分は、 `JsonSerializationSettings` をインスタンスフィールドに保存しておけばプレフィックスの結合とかが不要になるんじゃないかなと思いました。

せっかくクラスを作ってコンストラクタで new もしているので、利用すれば少しでもコードが簡潔になるんじゃないかなと思った次第です。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +    }
同じパッケージ内からしか参照されていないようなので、可視性はパッケージプライベートで十分かと思いましたが、publicである必要があるのでしょうか？
（他のプロジェクトで利用してる？）

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +    }
他から使用されていないので private でいいのでは、思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/PerformanceJsonLogFormatter.java
> +import java.util.*;
import は省略せず。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/PerformanceJsonLogFormatter.java
> + * </pre>
出力されるJSONのメンバーであることを説明する一文が欲しいです。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/ObjectSettings.java
> +    protected Map<String, String> getProps() {
パッケージプライベートでいいのでは、思いました。

可視性は private < パッケージプライベート < protected < public の順で広くなります。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +import java.util.*;
import は省略せずに。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + * BasicLogFormatterは、出力項目を指定してフォーマットを指定する。
> * BasicLogFormatterは、

JsonLogFormatter のタイポ。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + *     オブジェクトの型はMap&lt;String, Object&gt;でなければならない。<br>
> Map&amp;lt;String, Object&amp;gt;

`@code` ドックレットを使うと、 `<`, `>` をそのまま書けます（例: `{@code Map<String, Object>}`）。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + * requestId,userId,message,payload,stackTrace
ここで列挙されている項目と、上で個別で説明している項目の対応が分かりづらいと感じました。
（どの項目がデフォルトで出力されて、どの項目が出力されないのかが分かりづらい）

上の各項目を個別で説明しているところの記述を、以下のように工夫してみるのはいかがでしょう？

```
 * 出力項目の一覧を下記に示す。<br>
 * 名前の後ろに (default) と書いてある項目は、フォーマット指定が無い場合にデフォルトで出力される。
 * <pre>
 * date (default)
 *     このログ出力を要求した時点の日時。
 * logLevel (default)
 *     このログ出力のログレベル。
 *     デフォルトはLogLevel列挙型の名称を文言に使用する。
 *     文言はプロパティファイルの設定で変更することができる。
 * loggerName (default)
 *     このログ出力が対応するロガー設定の名称。
 *     このログ出力を呼び出した箇所に関わらず、プロパティファイル(log.properties)に記載したロガー名となる。
...
```

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + * </dl>
こっちは `<dl>` タグを使っているのなら、上の個別の項目を列挙している部分(`<pre>`を使ってるところ)も `<dl>` を使うのがいいのでは、と思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + *   <dt>writer.&lt;{@link LogWriter}の名称&gt;.formatter.label.&lt;{@link LogLevel}の名称の小文字&gt;<dt/>
テキストで見たときに、読みづらいと思いました。

Javadoc は、最終的には HTML に出力されますが、コード上で読むことも多いので、可能な限りテキストでも読みやすいようにしておいた方がいいです。

例：`{@code writer.<LogWriterの名称>.formatter.label.<LogLevelの名称の小文字>}`

`@link` が `@code` の入れ子になって使えなくなってしまいますが、読みやすさを優先してこちらの方がいいかと思います。
どうしてもリンクを載せたいのであれば、 `@see` でクラスの最後に載せておくでいいかと思います。

```java
 * @see LogWriter
 * @see LogLevel
 * @author Shuji Kitamura
```

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + *       指定しなければ{@link nablarch.core.text.json.JsonSerializationManager}を使用する。<dd/>
`JsonSerializationManager` をインタフェースにしたら、ここの実クラス名も変わる（`BasicJsonSerializationManager`?）ので、忘れず修正お願いします。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        if (StringUtil.isNullOrEmpty(targetsStr)) targetsStr = DEFAULT_TARGETS;
括弧対応漏れ

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +    }
privateでいいのでは？

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                        new InplaceMapEntries(message.substring(structuredMessagePrefix.length() + 1, message.length() - 1)));
末尾まで全て抽出する場合は、 `substring()` の第二引数は省略できます。

[String.substring(int)](https://docs.oracle.com/javase/jp/11/docs/api/java.base/java/lang/String.html#substring(int))

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        }
だいぶインデントが深くなって見づらくなってるので、早期リターンを使うと良いかなと思いました。

```java
if (context.getOptions() == null) {
    return;
}

boolean isIllegalObject;
for (Object option : context.getOptions()) {
...
```

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                                isIllegalObject = true;
どのキーに問題があったのかが分かりづらくなるので、ここでも個別にエラーログを出してあげた方が親切かなと思いました。
結果として、 `isIllegalObject` は不要になるイメージです。

```java
if (option instanceof Map) {
  for (Map.Entry<?, ?> entry : ((Map<?, ?>)option).entrySet()) {
    if (entry.getKey() instanceof String) {
      ...
    } else {
      errorSupport.outputFormatError(...);
    }
  }
} else {
  errorSupport.outputFormatError(...)
}
```

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/ApplicationSettingLogUtilTest.java
> +import static org.hamcrest.Matchers.*;
import は省略せずに。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/ApplicationSettingLogUtilTest.java
> +     * {@link nablarch.core.log.app.ApplicationSettingLogFormatter}を拡張した場合のテスト。
ここ、間違えて修正しちゃってませんか？

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/ApplicationSettingLogUtilTest.java
> +                is("$JSON${\"systemSettings\":{\"key3\":\"name3\uD83D\uDE0E\uD83D\uDE0E\"}}"));
こちらも、 JSON Path Assert を使った方法でテストしておいた方がいいと思いました。
この場合項目の順序などは一意ですが、スペースを含めるかようなテスト内容と関係のない変化でもテストが通らなくなってしまうので。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/ApplicationSettingLogUtilTest.java
> +        assertThat(message.substring(6), isJson(allOf(
`6` の意味をよりはっきり示すため、 `"$JSON$".length()` の方が伝わりやすいかなと思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/FailureJsonLogFormatterTest.java
> +        System.clearProperty("failureLogFormatter.contactFilePath");
親クラスの `LogTestSupport` でシステムプロパティのロールバックが行われているので、クリアは不要そうです。

https://github.com/nablarch/nablarch-log4j-adaptor/blob/master/src/test/java/nablarch/integration/log/LogTestSupport.java

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +        analysisStructuredTargets = getStructuredTargets(AppLogUtil.getProps(), PROPS_ANALYSIS_TARGETS);
引数で受け取っている `props` を使えば、 `AppLogUtil.getProps()` で取り直す必要はないのでは、と思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/FailureJsonLogFormatterTest.java
> +                withJsonPath("$", hasEntry("message", "FW000001メッセージerror")))));
`data` などの、デフォルトで出力対象になっていない項目が出力されていないこともチェックしておいた方がいいと思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/FailureJsonLogFormatterTest.java
> +        System.setProperty("failureLogFormatter.contactFilePath", "classpath:nablarch/core/log/app/failure-log-contact.properties");
`contact` が出力対象になっていないので、この設定は不要では？と思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/FailureJsonLogFormatterTest.java
> +        String failureCode = "FW000001";
`failureCode` の扱いについて、親クラスの `getFailureCode()` メソッドが使われていることが分かるようなテストケースがあった方がいいかなと思いました。

`getFailureCode()` 内の分岐を網羅する必要はないです。
「ちゃんと親クラスのメソッドを使って `failureCode` を処理してるよね」ってことを確認するためのテストです。

現状 `FW00001` のパターンしか見ていないので、 `getFailureCode()` を使ってなくてもテストが全てパスできる実装にすることが可能だと思います。
なので、 `getFailureCode()` を使ってないと失敗になるようなテストケースを１つ追加してあげることで、ちゃんと `getFailureCode()` を使ってるよ、ってことを保証してあげるイメージです。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +        JsonLogFormatterSupport support = new JsonLogFormatterSupport("xxxFormatter.", "default");
全てのテストメソッドで共通なので、インスタンスフィールドに抽出できると思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +    public void testgetSerializationManager() {
すごい細かいですけど、気づいてしまったので...

`get` の `g` は大文字ですね。
↓の `testgetSerializationManagerFromDefault` も同様。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +public class JsonLogFormatterSupportTest extends LogTestSupport {
テストが通っていないメソッド（コンストラクタ）があります。

- `JsonLogFormatterSupport(String)`
- `createStructuredObject()`
- `getStructuredMessage(List, CTX)`
- `getStructuredMessage(Object)`

テストは全ライン通している前提でレビューしているので、私の方でテストの実行は基本していません。
今回はたまたまテストケースが少ない気がして確かめたので気づけました。

他のプロジェクト・クラスも今一度全ライン、カバレッジが通っているか確認をお願いできますか？

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +        assertThat(support.getSerializationManager(), is(instanceOf(CustomJsonSerializationManager.class)));
このアサーションは必要ないと思いました（このテストケースが本当にアサートしたいのは144行目のアサーション）。

あと、なぜこれでシリアライズ時に `IOException` になるのかが初見だと分かりにくかったです。
`CustomJsonSerializationManager` の Javadoc を読んで理解できましたが、この実装だけだと気づくのに時間がかかりました。

Javadocのところに、「CustomJsonSerializationManagerはbooleanの値を処理するときにIOExceptionがスローされるようにしている」といった補足を入れておいていただくと、読む人の理解の助けになると思います。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        }
現在の実装では、任意の例外(`Exception`)をキャッチして標準エラー出力にログを出力し、フォーマット自体はエラーを表すメッセージを返しています。
しかし、 `JsonLogFormatter` が行う処理は、ログ出力の一連の処理の中の一部でしかありません。
その一部の処理が、任意の例外に対するハンドリングを実装していることに違和感を覚えました。

任意の例外のハンドリングは、もっとおおもとの、 `LogWriter` や `Logger` で行うべき処理だと思います。

実際、 `BasicLogFormatter` の `format()` では、[特に例外に関するハンドリングは何もありません](https://github.com/nablarch/nablarch-core-applog/blob/feature-NAB-392/src/main/java/nablarch/core/log/basic/BasicLogFormatter.java#L177)。
`LogWriter` の１つである `FileLogWriter` は、書き込み時に `IOException` が発生しても、[実行時例外に包んで再スローしています](https://github.com/nablarch/nablarch-core-applog/blob/feature-NAB-392/src/main/java/nablarch/core/log/basic/FileLogWriter.java#L178)。

任意の例外のハンドリングは `BasicLogger` で行われていて、[標準エラー出力にスタックトレースを書き出しています](https://github.com/nablarch/nablarch-core-applog/blob/feature-NAB-392/src/main/java/nablarch/core/log/basic/BasicLogger.java#L220)。

したがって、ここ（`JsonLogFormatter`）では任意の例外のハンドリングはせずに `IOException` だけを catch して、実行時例外に包んで再スローするのが正しいのではないかと思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +        return "format error";
ここの例外処理は、 `IOException` だけ catch して、実行時例外に包んで再スローだとまずいですか？
元になっている `ApplicationSettingLogFormatter` には、このような任意の例外を catch して標準エラー出力に書き出すような処理はなさそうなので、疑問に思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                else if (TARGET_NAME_PAYLOAD.equals(key)) { list.add(new PayloadBuilder(this)); }
`FormatErrorSupport` のインスタンスを `this` で固定で渡してしまっているので、`FormatErrorSupport` のインスタンスだけを独自実装に差し替えることができなくなってます。

これだと、浦上さんがおっしゃっていた「標準エラー出力に書き出す処理はinterfaceで抽象化しておいて差し替えられるようにしておきたいです。」が実現できないと思います。

`FormatErrorSupport` のインスタンスは、 `JsonLogFormatter` のインスタンスフィールドに持たせておいて、 `JsonSerializationManager` と同じ仕組みで実装クラスの切り替えができるようにしておく必要があると思います。

デフォルトの実装は `JsonLogFormatter` が実装するのではなく、 `StandardErrorFormatErrorSupport` のような標準エラー出力に書き出すデフォルト実装クラスを用意しておいて、それを利用するような形になると思います。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/PerformanceJsonLogFormatterTest.java
> +public class PerformanceJsonLogFormatterTest extends LogTestSupport {
`containsMemoryItem` の設定が正しく制御できているかを確認するテストケースが必要だと思います。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/PerformanceJsonLogFormatterTest.java
> +                withJsonPath("$", hasKey("endUsedMemory")))));
値も正しく設定できているか確認すべきだと思います。
値を取得している部分は独自に実装を書いているので。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/PerformanceJsonLogFormatterTest.java
> +                PerformanceJsonLogFormatter formatter = new PerformanceJsonLogFormatter();            }
メソッドの閉じ括弧が変なところに...

あと、 `formatter` 変数は使っていないので、

```java
new PerformanceJsonLogFormatter();
```

だけの記述で十分かなと思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +    }
「Json形式で正しくフォーマットできること」のテストであれば、下の `testFormatWithDefault()` が兼ねているので、このテストメソッドは不要ではないかと思いました。

`BasicCommitLoggerTest` の `testCustomLogItem()` を参考にしたものと思われますが、 このテストは `CustomLogFormatter` による実装の差し替えが動作するかをテストしているので、 JSON の書式を検証するテストケースで再利用するのは不適かなと思います。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +        }
例外を得るためにわざわざメソッドを複数に分けて呼び出しているのはなぜでしょうか？
スタックトレースを構築したいのかなと思いましたが、結局下ではエントリの有無しかチェックしていないようなので、普通に例外を new するだけでいいのでは？と思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +        LogContext context = new LogContext(loggerName, level, msg, error);
ここで生成した `context` は使われていません。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +                withJsonPath("$", hasKey("stackTrace")),
値もテストしてほしいです。
スタックトレース全体のテストを書くのはコードもごちゃごちゃして大変なので、 `BasicLogFormatter` のテストでやっているように `containsString()` で部分一致でテストを書くことは可能ですか？

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +            + ",bootProcess,processingSystem,requestId,userId,message,payload,stackTrace";
`runtimeLoggerName` もデフォルトの出力項目にいれてください。

`BasicLogFormatter` のデフォルトフォーマットに `runtimeLoggerName` が無いのは、 `runtimeLoggerName` が後から追加された項目だからです。
後方互換を維持するため、デフォルトフォーマットには `runtimeLoggerName` は追加されませんでした。

`JsonLogFormatter` は新規クラスなので、 `runtimeLoggerName` を入れていても問題ありません。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +    public void testFormatWithAllTargets() {
`runtimeLoggerName` をデフォルトの出力項目に入れることで、このテストと上の `testFormatWithDefault()` と差がなくなるかと思います。

なので、このメソッドは削除して、代わりに「指定した項目だけが出力されること」のテストケースを作成してください。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * 不正なターゲットが無視されること。
不正なターゲットの場合、警告ログを標準出力でいいので書き出すようにしませんか？

項目名をタイポしたときとかに、何も言わずにただ無視だけすると「なんで出力されないのか分からない」となりそうかなと思ったので、少しでもヒントを出すために警告ログくらいは出してあげて良いかなと思った次第です。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * 不正なOptionsが無視されること。
警告メッセージが `FormatErrorSupport` を介して出力されていることもテストしてください。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * 不正なOptionsが無視されること。
何が「不正」なのかをもう少し詳しく説明してあげた方が、テストコードを読む人が理解しやすいと思います。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        String prefix = settings.getProp(PROPS_SERIALIZATION_MANAGER_CLASS_NAME);
クラス名を入れる変数の名前が `prefix` なのはおかしいと思いました。

2021-03-17 07:29 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * シリアライズ管理クラスの変更ができること。
`CustomJsonSerializationManager` が、数値項目を文字列としてシリアライズするようカスタマイズされていることを補足していただけると、よりテストが読みやすくなると思いました。

このコードだけだと、期待される振る舞いが読み解きづらいと感じたので。

2021-03-17 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +            message = "\"log format error\"";
ダブルクォーテーションで囲う必要ってあるのでしょうか？

2021-03-18 00:56 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +    private static class FailureCodeBuilder implements JsonLogObjectBuilder<FailureLogContext> {
`JsonLogObjectBuilder` の実装クラスの可視性は public にしておいた方がいいかもと思いました。

元になっている各種ログの `LogItem` を実装したクラスをざっと見た感じ、いずれも protected 以上の可視性になっていました。
おそらく、拡張時に処理対象を項目単位で制御できるようにしたり、既存実装を継承して再利用できるようにすることが意図なのではないかと思います。

JSON 版のフォーマッタも同じ要領で拡張できるようにしておいたほうが、従来版のフォーマッタを拡張して利用しているユーザがいた場合に、移行しやすいんじゃないかと思いました。

2021-03-18 09:28 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +import java.util.*;
★後で一括修正

2021-03-18 09:28 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/FailureLogFormatter.java
> +import java.util.*;
★後で一括修正

2021-03-18 09:30 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/PerformanceJsonLogFormatter.java
> +import java.util.*;
★後で一括修正

2021-03-18 09:30 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +import java.util.*;
★後で一括修正

2021-03-18 09:33 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + *       指定しなければ{@link nablarch.core.text.json.JsonSerializationManager}を使用する。<dd/>
以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/ba0c30114d43e27426088e095c830cf7fa1b0d93

2021-03-18 09:43 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                        new InplaceMapEntries(message.substring(structuredMessagePrefix.length() + 1, message.length() - 1)));
先頭の中括弧と末尾の中括弧も除外する必要があります。
messageにセットされる文字列は以下のようになります。
$JSON${"key1":"val1","key2":"val2"}

2021-03-18 09:44 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/ApplicationSettingLogUtilTest.java
> +import static org.hamcrest.Matchers.*;
★後で一括修正

2021-03-18 09:49 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/ApplicationSettingLogUtilTest.java
> +     * {@link nablarch.core.log.app.ApplicationSettingLogFormatter}を拡張した場合のテスト。
設定でApplicationSettingLogFormatterの派生クラスに切り替えるテストなので、修正内容は正しいです。
今回ApplicationSettingLogUtilTestにテストを追加し、既存のコメントでエラーになっていた為、併せて修正しました。今回の修正とは直接は関係ない為、元に戻した方が宜しいでしょうか。

2021-03-18 09:49 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/ApplicationSettingLogUtilTest.java
> +     * {@link nablarch.core.log.app.ApplicationSettingLogFormatter}を拡張した場合のテスト。
(要相談)

2021-03-18 10:12 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/ApplicationSettingJsonLogFormatter.java
> + * </pre>
他の各種ログのJavadocについても、様々ご指摘を頂いており、記載レベルを統一したいと考えております。口頭で相談させて下さい。

2021-03-18 10:12 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/ApplicationSettingJsonLogFormatter.java
> + * </pre>
(要相談)

2021-03-18 10:13 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> + * </pre>
以下と合わせて相談させて下さい。
https://github.com/nablarch/nablarch-core-applog/pull/12#discussion_r596717610

2021-03-18 10:14 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> + * </pre>
(要相談)

2021-03-18 10:21 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/PerformanceJsonLogFormatter.java
> + * </pre>
以下と合わせて相談させて下さい。
https://github.com/nablarch/nablarch-core-applog/pull/12#discussion_r596717610

2021-03-18 10:22 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/PerformanceJsonLogFormatter.java
> + * </pre>
(要相談)

2021-03-18 10:37 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/ObjectSettings.java
> +    protected Map<String, String> getProps() {
アクセス指定忘れと間違えそうなので、下記のようなコメントの入れ方はありでしょうか。
`    /* package-private */ Map<String, String> getProps() {`

2021-03-18 10:37 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/ObjectSettings.java
> +    protected Map<String, String> getProps() {
(要相談)

2021-03-22 01:51 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/AppLogUtil.java
> +    public static final String getFilePath() {
以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/c0caca297e670f0e5f20b7236d619443a0a40208

なお、同じクラス内に既存メソッドで、静的メソッドに final つきのものがあります。併せて修正しておくべきでしょうか。

2021-03-22 01:51 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/ApplicationSettingJsonLogFormatter.java
> +    private final JsonLogFormatterSupport support = new JsonLogFormatterSupport(PROPS_PREFIX);
以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/511efe6b32d0e096323046aa2ca5ffd3110db504

2021-03-22 01:52 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +        if (StringUtil.isNullOrEmpty(targetsStr)) targetsStr = DEFAULT_TARGETS;
以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/21e841f12ad658986564dd8356a3c232320c9348

2021-03-22 02:27 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +     * @param prefix 各種ログの設定内容から値と取得するのに使用するプロパティ名のプリフィックス、
以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/89b06e922ab1723eddbf0b0a51683de9d521a4ee

2021-03-22 02:28 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +     * @return 出力項目
以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/89b06e922ab1723eddbf0b0a51683de9d521a4ee

2021-03-22 02:29 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        if (StringUtil.isNullOrEmpty(targetsStr)) targetsStr = DEFAULT_TARGETS;
以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/064cff57daec3736ad9a35073fa292cef2e654b6

2021-03-22 02:34 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/AppLogUtil.java
> +    public static final String getFilePath() {
(要相談)

2021-03-22 02:37 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/PerformanceJsonLogFormatter.java
> + * </pre>
(修正待ち)

2021-03-22 04:08 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/ApplicationSettingJsonLogFormatter.java
> + * </pre>
以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/776a96283d3de0a9a1a54808219007e799bcf91a

2021-03-22 04:08 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> + * </pre>
以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/776a96283d3de0a9a1a54808219007e799bcf91a

2021-03-22 06:56 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +     */
(修正待ち)

2021-03-22 06:57 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/JsonCommitLogger.java
> +        return "$JSON${\"commitCount\":" + count + '}';
(修正待ち)

2021-03-22 06:57 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +        String messagePrefix = AppLogUtil.getProps().get(prefix + PROPS_STRUCTURED_MESSAGE_PREFIX);
(修正待ち)

2021-03-22 06:57 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +    }
(修正待ち)

2021-03-22 06:57 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +    }
(修正待ち)

2021-03-22 06:58 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + * BasicLogFormatterは、出力項目を指定してフォーマットを指定する。
(修正待ち)

2021-03-22 06:58 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + *     オブジェクトの型はMap&lt;String, Object&gt;でなければならない。<br>
(修正待ち)

2021-03-22 06:58 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + * requestId,userId,message,payload,stackTrace
(修正待ち)

2021-03-22 06:58 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + * </dl>
(修正待ち)

2021-03-22 06:58 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + *   <dt>writer.&lt;{@link LogWriter}の名称&gt;.formatter.label.&lt;{@link LogLevel}の名称の小文字&gt;<dt/>
(修正待ち)

2021-03-22 06:58 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +    }
(修正待ち)

2021-03-22 06:59 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        }
(修正待ち)

2021-03-22 06:59 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                                isIllegalObject = true;
(修正待ち)

2021-03-22 06:59 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/ApplicationSettingLogUtilTest.java
> +                is("$JSON${\"systemSettings\":{\"key3\":\"name3\uD83D\uDE0E\uD83D\uDE0E\"}}"));
(修正待ち)

2021-03-22 07:00 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/ApplicationSettingLogUtilTest.java
> +        assertThat(message.substring(6), isJson(allOf(
(修正待ち)

2021-03-22 07:00 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/FailureJsonLogFormatterTest.java
> +        System.clearProperty("failureLogFormatter.contactFilePath");
(修正待ち)

2021-03-22 07:00 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +        analysisStructuredTargets = getStructuredTargets(AppLogUtil.getProps(), PROPS_ANALYSIS_TARGETS);
(修正待ち)

2021-03-22 07:00 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/FailureJsonLogFormatterTest.java
> +                withJsonPath("$", hasEntry("message", "FW000001メッセージerror")))));
(修正待ち)

2021-03-22 07:00 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/FailureJsonLogFormatterTest.java
> +        System.setProperty("failureLogFormatter.contactFilePath", "classpath:nablarch/core/log/app/failure-log-contact.properties");
(修正待ち)

2021-03-22 07:00 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/FailureJsonLogFormatterTest.java
> +        String failureCode = "FW000001";
(修正待ち)

2021-03-22 07:00 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +        JsonLogFormatterSupport support = new JsonLogFormatterSupport("xxxFormatter.", "default");
(修正待ち)

2021-03-22 07:00 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +    public void testgetSerializationManager() {
(修正待ち)

2021-03-22 07:00 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +public class JsonLogFormatterSupportTest extends LogTestSupport {
(修正待ち)

2021-03-22 07:01 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +        assertThat(support.getSerializationManager(), is(instanceOf(CustomJsonSerializationManager.class)));
(修正待ち)

2021-03-22 07:01 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        }
(修正待ち)

2021-03-22 07:01 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +        return "format error";
(修正待ち)

2021-03-22 07:01 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                else if (TARGET_NAME_PAYLOAD.equals(key)) { list.add(new PayloadBuilder(this)); }
(修正待ち)

2021-03-22 07:01 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/PerformanceJsonLogFormatterTest.java
> +public class PerformanceJsonLogFormatterTest extends LogTestSupport {
(修正待ち)

2021-03-22 07:01 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/PerformanceJsonLogFormatterTest.java
> +                withJsonPath("$", hasKey("endUsedMemory")))));
(修正待ち)

2021-03-22 07:01 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/PerformanceJsonLogFormatterTest.java
> +                PerformanceJsonLogFormatter formatter = new PerformanceJsonLogFormatter();            }
(修正待ち)

2021-03-22 07:01 UTC, shuji-k commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +    }
(修正待ち)

2021-03-22 07:02 UTC, shuji-k commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +        }
(修正待ち)

2021-03-22 07:02 UTC, shuji-k commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +                withJsonPath("$", hasKey("stackTrace")),
(修正待ち)

2021-03-22 07:02 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +            + ",bootProcess,processingSystem,requestId,userId,message,payload,stackTrace";
(修正待ち)

2021-03-22 07:02 UTC, shuji-k commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +    public void testFormatWithAllTargets() {
(修正待ち)

2021-03-22 07:02 UTC, shuji-k commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * 不正なターゲットが無視されること。
(修正待ち)

2021-03-22 07:02 UTC, shuji-k commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * 不正なOptionsが無視されること。
(修正待ち)

2021-03-22 07:02 UTC, shuji-k commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * 不正なOptionsが無視されること。
(修正待ち)

2021-03-22 07:02 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        String prefix = settings.getProp(PROPS_SERIALIZATION_MANAGER_CLASS_NAME);
(修正待ち)

2021-03-22 07:02 UTC, shuji-k commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * シリアライズ管理クラスの変更ができること。
(修正待ち)

2021-03-22 07:08 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +            message = "\"log format error\"";
messageをダブルクォーテーションで囲うことにより、生成されるログはJsonの構文としての形を維持できるため、そのようにしています。
`{"date": "2021-03-22 16:00:00.000", "message":"log format error"}` のようになります。（ダブルクォーテーションが無い場合は、JSONとしてログを読み込むと構文エラーになります。）

2021-03-22 07:08 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +    private static class FailureCodeBuilder implements JsonLogObjectBuilder<FailureLogContext> {
(修正待ち)

2021-03-23 04:06 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + *     オブジェクトの型はMap&lt;String, Object&gt;でなければならない。<br>
(要確認)

2021-03-23 04:23 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +        JsonLogFormatterSupport support = new JsonLogFormatterSupport("xxxFormatter.", "default");
(要相談)

2021-03-23 04:44 UTC, shuji-k commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +        LogContext context = new LogContext(loggerName, level, msg, error);
以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/d313d76a0a42ead3758f5c1c8fa099c065a8df0e

2021-03-23 07:11 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +    private static class FailureCodeBuilder implements JsonLogObjectBuilder<FailureLogContext> {
(要相談)

2021-03-23 07:20 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + * </dl>
(要相談)

2021-03-23 07:38 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                                isIllegalObject = true;
(要相談)

2021-03-23 08:37 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        }
(要相談)

2021-03-24 00:37 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +public class JsonLogFormatterSupportTest extends LogTestSupport {
(要相談)

2021-03-24 02:39 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/ObjectSettings.java
> +    protected Map<String, String> getProps() {
(修正待ち)

2021-03-24 02:40 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + *     オブジェクトの型はMap&lt;String, Object&gt;でなければならない。<br>
(修正待ち)

2021-03-24 02:43 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                                isIllegalObject = true;
(修正待ち)

2021-03-24 02:49 UTC, shuji-k commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        }
(修正待ち)

2021-03-24 02:51 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> +    private static class FailureCodeBuilder implements JsonLogObjectBuilder<FailureLogContext> {
(修正待ち)

2021-03-24 06:31 UTC, shuji-k commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +        String messagePrefix = AppLogUtil.getProps().get(prefix + PROPS_STRUCTURED_MESSAGE_PREFIX);
(修正待ち)

2021-03-24 10:22 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +public class JsonLogFormatterSupportTest extends LogTestSupport {
(修正待ち)

2021-03-26 06:31 UTC, shuji-k commented on src/test/java/nablarch/core/log/app/PerformanceJsonLogFormatterTest.java
> +public class PerformanceJsonLogFormatterTest extends LogTestSupport {
以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/62d96bf432861d1f5898159cdb869895e592f447

2021-03-31 05:21 UTC, shuji-k commented
各種ログ出力の為のMapへのメンバーの直接挿入処理について、独自実装に当たる為、nablarch-core-appにて対応すべきとのご指摘について、以下で対応しました。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/ac092b444e03cc45580c6e2dc1c4201021b644e8

2021-04-01 02:48 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/ApplicationSettingJsonLogFormatter.java
> + * </pre>
> として出力内容をs呈するが、

誤記あり

2021-04-01 02:50 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> + * </pre>
> として出力内容をs呈するが、

誤記あり（おそらく「設定する」）

2021-04-01 04:23 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/PerformanceJsonLogFormatter.java
> +import java.util.*;
書かれているコミットには `PerformanceJsonLogFormatter` は含まれていないけど、最新のコミットを見て省略が除去されていることを確認。

2021-04-01 04:24 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/PerformanceJsonLogFormatter.java
> + * </pre>
> として出力内容をs呈するが、

誤記あり（おそらく「設定する」）

2021-04-01 04:25 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +import java.util.*;
書かれているコミットには `JsonLogFormatter` は含まれていないが、最新のコミットで省略が修正されていることを確認。

2021-04-01 04:32 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + * </dl>
**補足追記**
実際に出力されたものを見ると、確かに `<dl>` を使った方が見た目が分かりづらいスタイルになっていたので、既存の `BasicLogFormatter` と同じ形にしておくことにした。

2021-04-01 04:37 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + *   <dt>writer.&lt;{@link LogWriter}の名称&gt;.formatter.label.&lt;{@link LogLevel}の名称の小文字&gt;<dt/>
`writer.` からはじまる全体がプロパティの名前（プログラム要素）を指すので、例に挙げたように全体を `@code` で括った方がいいと思います。
`<LogLevelの名称の小文字>` の部分が、対応から漏れてますし。

2021-04-01 04:39 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                        new InplaceMapEntries(message.substring(structuredMessagePrefix.length() + 1, message.length() - 1)));
私の勘違いでした。
指摘を取り下げます。

**補足**

`$JSON${"key1":"val1","key2":"val2"}` から `"key1":"val1","key2":"val2"` を切り出している。

2021-04-01 04:44 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                                isIllegalObject = true;
```java
                            if (entry.getKey() == null) {
                                illegalMessage.append("null");
                            } else {
                                illegalMessage.append(entry.getKey().toString());
                            }
```

ここは、以下のように実装しても同じ動きになる。
（key が null なら "null" という文字列が追加されるし、そうでなければ toString() の結果が追加される）

```java
illegalMessage.append(entry.getKey());
```

2021-04-01 04:51 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                                isIllegalObject = true;
よく見たら以下も参考演算子不要。

```java
                    errorSupport.outputFormatError("objects in options must be Map<String, Object>."
                            + "[" + (option == null ? "null" : option.toString()) + "]");
```

2021-04-01 05:28 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +public class JsonLogFormatterSupportTest extends LogTestSupport {
> カバレッジが100%ではない件については、以下で対応しました。
> 64afe92

```java
    @Test
    public void testSerializeError() {
        // note CustomJsonSerializationManagerはbooleanを処理する際に、必ずIOExceptionをスローする
        props.put("xxxFormatter.jsonSerializationManagerClassName",
                "nablarch.core.log.basic.CustomJsonSerializationManager");
        final JsonLogFormatterSupport support = createJsonLogFormatterSupport();

        final Map<String, Object> structuredObject = new HashMap<String, Object>();
        structuredObject.put("key", true);

        Exception e = assertThrows(RuntimeException.class, new ThrowingRunnable() {
            @Override
            public void run() throws Throwable {
                support.getStructuredMessage(structuredObject);
            }
        });
```

テストが中途半端なところで終わってしまっていて、何も検証できていないです。

2021-04-01 05:35 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        }
スローされた `RuntimeException` に、原因となった `IOException` がセットされていることをまで確認するようなテスト内容にしてほしいです。

2021-04-01 05:39 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +        return "format error";
```java
    @Test
    public void testSerializeError() {
        ...

        Exception e = assertThrows(RuntimeException.class, new ThrowingRunnable() {
            @Override
            public void run() throws Throwable {
                support.getStructuredMessage(structuredObject);
            }
        });
    }
```

スローされた例外に、原因となった `IOException` がセットされていることを確認してほしいです。

2021-04-01 05:56 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                else if (TARGET_NAME_PAYLOAD.equals(key)) { list.add(new PayloadBuilder(this)); }
`JsonSerializationManager` はプロパティで実装クラスを差し替えられるようにしているのに、 `FormatErrorSupport` はそうなっていない（差し替えたい場合は `JsonLogFormatter` を継承したクラスを作って `createFormatErrorSupport()` をオーバーライドする必要がある）。

手法がそろっていないことに違和感がある（`JsonSerializationManager` の方が差し替えの可能性が高い？　実際のところ、そんなに差し替え頻度が高いとは思えない）。

実は、 `JsonSerializationManager` の差し替えもメソッドオーバーライドで十分なのでは、と思えてきた。

他の人の意見も聞きたい。

2021-04-01 07:05 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/PerformanceJsonLogFormatterTest.java
> +public class PerformanceJsonLogFormatterTest extends LogTestSupport {
```java
        // note ログコンテキストをMockにしている為、setterの呼び出しを確認
        new Verifications() {{
            context.setPoint("point0001"); minTimes(1);
            context.setResult("success"); minTimes(1);
            context.setStartTime(anyLong); minTimes(1);
            context.setEndTime(anyLong); minTimes(1);
            context.setMaxMemory(anyLong); minTimes(1);
            context.setStartFreeMemory(anyLong); minTimes(1);
            context.setEndFreeMemory(anyLong); minTimes(1);
            context.setStartUsedMemory(anyLong); minTimes(1);
            context.setEndUsedMemory(anyLong); minTimes(1);
        }};
```

- `testFormat()` がテストしているのは、 JSON ログに出力された値が全てコンテキストから取得した値を利用していることだと思うので、 Setter が呼び出されているかどうかまではテストする必要はないかなと思います
- コンテキストに値をセットしている実装は親クラスにあるので、それ（コンテキストへの値の設定）のテストは親クラスのテストにあれば十分だと思います

---

```java
    @Test
    public void testFormatWithTargets() {
        ...

        // note nullが返るとキーごとスキップされるため、getterが呼び出しされていないこも確認
        new Verifications() {{
            context.getResult(); times = 0;
            context.getStartTime(); times = 0;
            context.getEndTime(); times = 0;
            context.getExecutionTime(); times = 0;
            context.getMaxMemory(); times = 0;
            context.getStartFreeMemory(); times = 0;
            context.getEndFreeMemory(); times = 0;
            context.getStartUsedMemory(); times = 0;
            context.getEndUsedMemory(); times = 0;
        }};
    }
```

- コンテキストをテスト全体を通してモック化したことで、本来なら必要ない `Verifications` が追加されてしまっているように思えます
  - モック化していなければ null は返さないので普通にテストが成り立っていたのに、モック化して null を返すようになったことで、呼ばれてないことまでテストしなければならなくなっている
- 本当にモック化しないとテストできないテストケースというのは、この中では `testFormat()` だけかなと思います
  - MBean や `System` からとった値を使用するため、モック化しないとテストが難しい
- コンテキストのモック化は `testFormat()` だけに絞って、他はモック(jmockit)を使用しないようにした方がいいかなと思いました
  - jmockit によるモック化は強力な反面、なんでもできすぎるため逆にテストの構造が複雑化するようなこともあるので、使用は最小限に留める方が良いです
- その場合（利用を `testFormat()` に限定した場合）、 `testFormatWithoutMemory()` などのメモリ項目のテストをどうするかですけど、こちらはモックを使わずに「ターゲットが指定されたときに、JSONログに当該メンバーが出力されていること」をテストすればいいかと思います
  - このときは、メンバーの存在だけチェックして、値のテストは要らないと思います（値の確認は `testFormat()` でテストしているので）

2021-04-01 07:06 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/PerformanceJsonLogFormatterTest.java
> +                withJsonPath("$", hasKey("endUsedMemory")))));
https://github.com/nablarch/nablarch-core-applog/pull/12#discussion_r605422262 に集約。

2021-04-01 07:18 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +                withJsonPath("$", hasKey("stackTrace")),
**補足**

正規表現の Matcher は、 Hamcrest の ver 2.x で初めて追加されたらしく、 1.3 を使っている現在の Nablarch プロジェクトでは利用できない。。。

http://hamcrest.org/JavaHamcrest/javadoc/2.0.0.0/org/hamcrest/text/MatchesPattern.html

2021-04-01 07:26 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * 不正なターゲットが無視されること。
```
                else {
                    System.err.println(
                            String.format("JsonLogFormatter : [%s] is unknown target. property name = [%s.%s]",
                                    key, settings.getName(), PROPS_TARGETS));
                }
```

- optionsの型が不正だった場合のメッセージ出力は `FormatErrorSupport` を使って抽象化されているのに対して、こちらの出力は抽象化されていないことに違和感を覚えました
- おそらく、「フォーマットエラーじゃないから別にしている」という判断だと思うのですが、「本来なら正しくない状態にあることをメッセージ出力で知らせる」という目的は同じだと思うので、別扱いにはしないほうが親切かなと思います
- そもそも `FormatErrorSupport` という名前が用途を制限してしまっていると思うので、「警告メッセージの出力を行うモノ」的な名前のインタフェースにして、ここの部分も処理を委譲すればいいのではないかと思いました

2021-04-01 07:32 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * 不正なOptionsが無視されること。
```java
        ByteArrayOutputStream snatchedErr = new ByteArrayOutputStream();
        System.setErr(new PrintStream(snatchedErr));

        String message = formatter.format(new LogContext(loggerName, level, msg, error,
                payload1, payload2, payload3));

        System.err.flush();
        assertThat(snatchedErr.toString(), is(
                "objects in options must be Map<String, Object>. : [test]" + System.getProperty("line.separator")
                + "objects in options must be Map<String, Object>. : [null]" + System.getProperty("line.separator")));
```

- これだと、「標準エラー出力に出力されたこと」のテストになってしまいます
- `FormatErrorSupport` のテスト用クラスを作って、`outputFormatError()` に適切なメッセージが渡されたかどうかをテストするような形式にすべきです

2021-04-01 07:38 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +            message = "\"log format error\"";
フォーマットエラー時は例外をスローして中断するようになったので、この実装はなくなった。

2021-04-02 00:11 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/FailureJsonLogFormatter.java
> + * </pre>
以下で修正
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/79490fbc2939c1567b7e03aeb8ae8fd99efe04c7

2021-04-02 00:11 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/PerformanceJsonLogFormatter.java
> + * </pre>
以下で修正
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/79490fbc2939c1567b7e03aeb8ae8fd99efe04c7

2021-04-02 00:15 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> + *   <dt>writer.&lt;{@link LogWriter}の名称&gt;.formatter.label.&lt;{@link LogLevel}の名称の小文字&gt;<dt/>
以下で対応
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/02279f9b0f3324cd1084e16a9c6f564b7243e5a1

2021-04-02 07:12 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                                isIllegalObject = true;
以下で対応。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/b6a178d3d724fcbfde61f17ccc84aa84e0d0f019

2021-04-02 07:19 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/JsonLogFormatterSupportTest.java
> +public class JsonLogFormatterSupportTest extends LogTestSupport {
スローされた `RuntimeException` の `cause` に、原因となった `IOException` がセットされていることを確認するようにテストを修正。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/60e829fe922d2919c27daa6a993872d73ff08796

2021-04-02 07:28 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +        }
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/187ac8273b3bba522ec63ea209d096197fe20531
原因例外をテストするように修正。

https://github.com/nablarch/nablarch-core-applog/pull/12/commits/858004521ec1cc5349bf1f8a8e530609e0718e9b
また、`assertThrows()` の中に処理が多く、例外が投げられると想定している処理がどれなのかわかりにくいと感じたので、関係ない前処理を外に出すように修正。

2021-04-02 07:29 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/JsonLogFormatterSupport.java
> +        return "format error";
https://github.com/nablarch/nablarch-core-applog/pull/12#discussion_r606108670 で対応済み。

2021-04-02 07:57 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * 不正なOptionsが無視されること。
以下で対応。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/f22493963d9f1a37ea72a11ce748c41ef60776c8

2021-04-06 07:48 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/ApplicationSettingJsonLogFormatter.java
> +public class ApplicationSettingJsonLogFormatter extends ApplicationSettingLogFormatter {
[nablarch-fw-standalone の指摘](https://github.com/nablarch/nablarch-fw-standalone/pull/13#discussion_r596471435)後に気づいたが、本クラスも他のフォーマッタ同様に `JsonLogObjectBuilder` を使った形式に修正すべき。

2021-04-07 07:00 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/app/PerformanceJsonLogFormatterTest.java
> +public class PerformanceJsonLogFormatterTest extends LogTestSupport {
以下で対応。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/b42ee7d6650d405ab8d96c0fccab624855cad457
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/864729137402b6eaaf3023a6cbc8e1df0ff89355

2021-04-07 07:03 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                else if (TARGET_NAME_PAYLOAD.equals(key)) { list.add(new PayloadBuilder(this)); }
`JsonSerializationManager` を差し替えたくなる頻度は少なそうなので、オーバーライド方式で行くことになった。

2021-04-07 07:46 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/JsonLogFormatter.java
> +                else if (TARGET_NAME_PAYLOAD.equals(key)) { list.add(new PayloadBuilder(this)); }
以下で対応。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/d99a279eee5b7409f229fb6d44052fc35e44e46f

2021-04-07 07:52 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * 不正なターゲットが無視されること。
https://github.com/nablarch/nablarch-core-jdbc/pull/54#discussion_r608421259

上記議論において、サポートされていないターゲットが指定された場合はエラーにすることになったので、[1つ上のコメント](https://github.com/nablarch/nablarch-core-applog/pull/12#discussion_r605433152)は取り下げ。

代わりに、エラーにする対応が必要。

2021-04-07 08:02 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/JsonLogFormatterTest.java
> +     * 不正なターゲットが無視されること。
以下でエラーをスローするように修正。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/fa7270341d8befc365d859ebc75e685dc3a565b1

2021-04-09 08:11 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/app/ApplicationSettingJsonLogFormatter.java
> +public class ApplicationSettingJsonLogFormatter extends ApplicationSettingLogFormatter {
以下で対応。
https://github.com/nablarch/nablarch-core-applog/pull/12/commits/a54f88b7b65b075961bbcddc1ad1bf0e379facc2

`getAppSettingsLogMsg()` で `businessDate` をターゲットに指定できるべきかどうか悩んだが、値が取得できないわけではないのでサポートできることにして指定されてもエラーにはしないようにした。

2021-11-17 06:23 UTC, opengl-8080 requested changes
> AppLogMapToJsonSerializer

実装の大部分が nablarch-core にある `MapToJsonSerializer` と重複しているのが気になりました。

コピーになってしまっているのは、 `MapToJsonSerializer` で定義されている定数が private でサブクラスから参照できないことが理由かと思います。
さすがにコピーになっているデメリットの方が大きいと思うので、定数など参照が必要なものを protected に修正してサブクラス化するのがいいかと思いました。

その場合、このクラスは `serialize()` メソッドのオーバーライドだけで済むようになるかと思います。
※`serialize()` メソッドの差分があるところだけメソッド抽出してオーバーライドすればさらに共通部分を切り出せますが、あまりにこのクラスに特化した設計になってしまって違和感があるので、 `serialize()` をオーバーライドくらいでいいかなと思います(`isFirst` の扱いが難しいので、一部だけ切り出すのも難しいかも)。

ただし、この対応をする場合は nablarch-core にある他の `JsonSerializer` の実装も、同じようにサブクラスで拡張ができるように定数などを protected に修正しないとバランスが取れなくなると思います。

2021-11-17 06:27 UTC, opengl-8080 commented
https://github.com/nablarch/nablarch-core-applog/pull/12#pullrequestreview-808155571 に対する修正を、以下で対応。

- https://github.com/nablarch/nablarch-core-applog/pull/12/commits/116d8d80a52e7d5b2a1adeb7b276a075a3dfca14
- https://github.com/nablarch/nablarch-core/pull/33/commits/5b8facc115b25d45c4a2c2b632e67c014a693029

2021-12-09 02:29 UTC, opengl-8080 approved these changes

2021-12-09 02:30 UTC, merged