日付でファイルローテーションできるLogWriterの提供
nablarch/nablarch-core-applog pull request #17
Opened 2023-02-22 06:02 UTC by takikunxo

2023-02-27 01:55 UTC, kumagoro1202 requested changes

2023-02-27 01:55 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + * <li>日付が変わったら、出力ファイルを自動で切り替える。</li>
これは両方を書くんじゃなく、ファイルをローテーションできる。ローテーションのルールは差し替えることができる。といったようなことを書くようにしてください。デフォルトではファイルサイズで切り替えることも記載してください。

2023-02-27 01:55 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + *     ファイルサイズごとにローテーションする{@link FileSizeRotatePolicy}を提供している。<br>
指定しなかった場合（デフォルト）についても記載してください。

2023-02-27 01:55 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + *     ファイルサイズごとにローテーションする{@link FileSizeRotatePolicy}を提供している。<br>
あと標準で～という部分は不要です。今後RotatePolicyの実装クラスを増やすことがあれば、このJavadocコメントも直さなければいけなくなるので。

2023-02-27 01:55 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + *     このオプションは、rotatePolicyに{@link DateRotatePolicy}が設定されている場合に有効である。
1文に色々な情報を込めると読み手の負荷が高いです。
こんな感じかなと思います。
```
 * <dd>日付タイプ。オプション。<br>
 *     日付ごとのローテーション判定に必要な日付の種類を指定する。<br>
 *     システム日時を使用する場合はsystem、業務日付を使用する場合はbusinessを指定する。<br>
 *     デフォルトはsystem。<br>
 *     このオプションは、rotatePolicyに{@link DateRotatePolicy}が設定されている場合に有効である。</dd>
```

2023-02-27 01:55 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + *     このオプションは、rotatePolicyに{@link DateRotatePolicy}が設定されている場合に有効である。
HTMLの文法にあってない（閉じタグない）ところは直してください。

2023-02-27 01:55 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +        rotatePolicy.initialize(settings);
classNameにデフォルトのクラスのFQCNを入れるのではなくデフォルトのクラスはnewするようにしてください。
参考：https://github.com/nablarch/nablarch-core-applog/blob/master/src/main/java/nablarch/core/log/app/FailureLogUtil.java#L37-L43

2023-02-27 01:55 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +     * CURRENT DATE       = [&lt;現在日付&gt;]<br>
これはRotatePolicyの実装によるのでこのクラスには書かないでください。RotatePolicyのgetSettingsが返す値も一緒に出すといったようなことを書いてください。
極力インタフェースで切り出したものの実装クラスに関することは書かないようにしてください。

2023-02-27 01:55 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private Calendar cl;
Calendarを再利用するのはわかりにくいので使うたびにnewする。

2023-02-27 01:55 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +        String newFilePath = rotatePolicy.getNewFilePath();
needsRotateを呼ぶたびにインスタンス変数で持ったnewFilePathが変わるのは気持ち悪い。
rotatePolicyで新しいファイル名を予約するようなメソッドを呼び出してからrotateの引数にわたすか、rotateの戻り値でローテート後のファイル名を戻すかにしてください。

2023-02-27 01:55 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private Calendar cl;
インスタンス変数の状態を考えながらメソッドを使わないといけないのは無駄に頭のリソースを使うことになってしんどいので、メソッド内でnewするようにしてください。

2023-02-27 06:01 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + * <li>日付が変わったら、出力ファイルを自動で切り替える。</li>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/371f3249d8b50b8e69ea6e6f0ba3d76569fdf5ef)で修正しております。

2023-02-27 06:01 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + *     ファイルサイズごとにローテーションする{@link FileSizeRotatePolicy}を提供している。<br>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/371f3249d8b50b8e69ea6e6f0ba3d76569fdf5ef)で修正しております。

2023-02-27 06:02 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + *     このオプションは、rotatePolicyに{@link DateRotatePolicy}が設定されている場合に有効である。
文法については、[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/371f3249d8b50b8e69ea6e6f0ba3d76569fdf5ef)で修正しております。

文章の修正については、[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/ac9799b8cd65367a59abf6f504f675b36d1bf5c7)で修正しております。

2023-02-27 06:03 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +        rotatePolicy.initialize(settings);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/f836a3099cb247633be3364f2763de923d56c969)で修正しております。

2023-02-27 06:04 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +        rotatePolicy.initialize(settings);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/67b8447d110db05feeae63566169c0d0d1a4c085)で修正しております。

2023-02-27 06:04 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +     * CURRENT DATE       = [&lt;現在日付&gt;]<br>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/371f3249d8b50b8e69ea6e6f0ba3d76569fdf5ef)で修正しております。

2023-02-27 06:04 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private Calendar cl;
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/f836a3099cb247633be3364f2763de923d56c969)で修正しております。

2023-02-27 06:05 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +        String newFilePath = rotatePolicy.getNewFilePath();
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/0b905e3282c074f943cfa9d9af1d3619c157cfb0)で修正しております。

上記の修正では、rotateの引数にわたしていなかったので[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/371f3249d8b50b8e69ea6e6f0ba3d76569fdf5ef)で引数として渡すようにしております。

2023-02-27 08:24 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private Calendar cl;
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/f8483f0427e73f5602dadc93b693b58bf187389c#diff-9aa96aac354607dc8e9f905606ef24d10beb105f542bda43d8589986921d8cc6)で最後の自動テストで不具合とのなっていた箇所があったので修正しております。

2023-02-27 08:25 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +        rotatePolicy.initialize(settings);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/f8483f0427e73f5602dadc93b693b58bf187389c#diff-9045cd968a098244a157637ede51356a4c51fc85121aba4e57af65f5a699a788)で最後の自動テストで不具合となっていた箇所があったので修正しております。

2023-02-27 12:09 UTC, kumagoro1202 requested changes

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + *     このオプションは、rotatePolicyに{@link DateRotatePolicy}が設定されている場合に有効である。</dd>
この部分は各RotatePolicyの実装クラスに記載してください。ここでは利用するRotatePolicyによって追加の設定があるということを記載してください。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/RotatePolicy.java
> +     * ファイルサイズによるローテーションなどを独自で実装したい場合に使用する。
ファイルサイズによるローテーションなどをというのはインタフェースのJavadocとしてはピンポイントすぎて違和感を覚えます。具体的な内容を書いた方がいい場合もありますが、これだと具体的というより限定的な印象を受けました。もう少し汎用的に「書き込むメッセージに応じて処理を実装したい場合」などがいいと思いました。
これ以外のファイルサイズによる～やシステム日付の取得など～といった具体的な用法を書いている部分についても同様です。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/RotatePolicy.java
> +    void initialize(ObjectSettings settings, Charset charset);
FileSizeRotatePolicyでCharsetを使いたいから引数に入れたんだと思いますが、CharsetはObjectSettingsから算出できるものなのでCharsetだけ別で渡すことに違和感があります。needsRotateやonWriteのメソッド引数に渡さずインスタンス変数でCharsetを持つという方針は良いと思うので、FileLogWriter同様ObjectSettingsからCharsetを取得するようにした方がいいと思います。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * 日付ごとのローテーション判定に必要な日付を、dateTypeにsystemと設定されていればシステム日次から、
typo システム日時

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            dt = "system";
dateTypeは必須ではないので、getPropで取得した後null判定を入れてください。
Exceptionをキャッチして処理を分岐するのは、無駄なコストがかかるのとExceptionを握りつぶすことになるので良い実装ではないです。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            String currentDateSt = BusinessDateUtil.getDate();
業務日付を使う場合はセグメントを指定できた方が良いです。
settingsでセグメントが指定されたらBusinessDateUtil.getDate(segment)を指定されていなかったらBusinessDateUtil.getDate()でデフォルトセグメントが使われるようにしてください。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    }
Calendarを返すのではなくDateを返すようにした方がいいです。全部の使用箇所で
```
Calendar cl = calcNextUpdateDate(currentDate);
nextUpdateDate = cl.getTime();
```
となっているのは違和感です。nextUpdateDateを計算するのだから戻り値はnextUpdateDateと同じ型にした方がわかりやすいです。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        }
ここはFileインスタンスを受け取るonOpenFileの中でやった方がいいのではと思いました。ここだけsettingsをもとにした初期化処理ではなくファイルの属性による初期化処理なのでonOpenFileの方が合っていると思います。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    }
【要議論】これもDate型を返したほうがいいです。またメソッド名がわかりにくいです。名前だけ見るとrotatedFilePathに代入するStringを返すように見えます。メソッド化するメリットもあまり感じずdecideRotatedFilePathにインラインで書いてもいいのではないでしょうか。引数のnextUpdateDateもメソッド引数で渡していますが呼び出し元ではインスタンス変数をメソッド引数に渡していて違和感があります。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        Date newFileDate = cl.getTime();
newFileDateという名前は混乱します。ローテーション後のファイルの日付なので古い日時が入るはずでそれをnewと呼ぶことに違和感があります。previousDateとかかな。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        }
引数で渡されたファイル名をメソッドの中で変えるのは予測できない動きなので良くないです。またdecideRotatedFilePathの中でこれをしておかないと、ログファイルに出力されたファイル名と実際にローテーションされた後のファイル名が乖離してしまいます。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +                .append(rotatePolicy.getSettings())
設定されたrotatePolicyの実装クラス名も出したほうがいいと思います。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        return "\tFILE AUTO CHANGE   = [" + true + "]" + Logger.LS;
この実装では自動で切り替えるか否かは選択できないのでこの情報は不要だと思います。それよりもdateTypeはこの実装固有の情報なので出すべきではないでしょうか。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        nextUpdateDate = cl.getTime();
nextUpdateDateの更新はrotateの中でやる話になっていたはずです。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        return !nextUpdateDate.after(currentDate);
booleanの反転は理解しにくくなるのでなるべく使わない方が良いです。
`currentDate.after(nextUpdateDate)`にするか`nextUpdateDate.before(currentDate)`にするべきです。前者のほうが文脈的には理解しやすく感じます。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> + * ファイルの最大サイズ以上になる場合は、ログのローテーションを行う。<br>
１文のなかで「～場合は、～場合は～」と続くと読みにくい文章になります。「設定したファイルの最大サイズを超える場合にローテーションを行う。ファイルの最大サイズが指定されていない場合は、ローテーションしない。」で十分意味がわかるかと思います。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            throw new IllegalArgumentException("dateType was invalid");
【要議論】想定しないdateTypeを指定されたときはSYSTEMに寄せていいのではと思いました。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +     * ファイルの最大サイズ以上になる場合は、ローテーションが必要と判定する。<br>
クラスのJavadocで書いた指摘同様。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +     * ローテーションが必要場合は、併せてローテーション実施時のリネーム先のファイルパスを更新する。<br>
この処理はやめたものじゃないですか？

2023-02-27 12:09 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }};
匿名クラスとして初期化するのではなく、setUpメソッドの中で値をsetするようにしてください。

2023-02-27 12:09 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }};
また変数の型はインタフェースで宣言しておくほうが良いです。

2023-02-27 23:51 UTC, kumagoro1202 commented
log/.gitkeepを削除してしまっていますが必要なファイルなので復元してください。

2023-02-28 00:43 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/RotatePolicy.java
> +     * ファイルサイズによるローテーションなどを独自で実装したい場合に使用する。
これは取り下げます。

2023-02-28 00:57 UTC, kumagoro1202 requested changes

2023-02-28 00:57 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +        rotatePolicy.setupIfNeeded();
synchronizedブロック内に入れた方がいい。

2023-02-28 00:57 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/RotatePolicy.java
> +    void setupIfNeeded();
setUpAfterSystemRepositoryInitialized
システムリポジトリが構築された後であることをメソッド名で表す。

2023-02-28 00:57 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +        rotatePolicy.setupIfNeeded();
最初の書き込みかどうかをFileLogWriter側で制御する。

2023-02-28 01:04 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/RotatePolicy.java
> +    void initialize(ObjectSettings settings, Charset charset);
ObjectSettingsから取得するという指摘は取り下げ。

2023-02-28 01:05 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/RotatePolicy.java
> +    void initialize(ObjectSettings settings, Charset charset);
initializeで渡すより、必要としているneedsRotate、onWriteのメソッド引数として対象のStringと一緒に渡した方がわかりやすい。

2023-02-28 01:08 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            throw new IllegalArgumentException("dateType was invalid");
取り下げ。

2023-02-28 01:15 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        }
取り下げ。

2023-02-28 01:20 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        Date newFileDate = cl.getTime();
rotatedFileDate

2023-02-28 05:52 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + *     このオプションは、rotatePolicyに{@link DateRotatePolicy}が設定されている場合に有効である。</dd>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/e7b648d15e3b30bf561e7367d28af1a6d7e220f1)で修正しております。

2023-02-28 05:53 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/RotatePolicy.java
> +    void initialize(ObjectSettings settings, Charset charset);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/c483832103848578ae6d18c3d7a7934ffbbb9a37)で修正しております。

2023-02-28 05:53 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            dt = "system";
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/555c970cf6151b419c19c655515038f61f0510da)で修正しております。

2023-02-28 05:54 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/9ebbf5d01ad41166c3ecd881ed08935556eb7c6c)で修正しております。

2023-02-28 05:54 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/54bbff31c8bacd3b322eef567f309648bc7d5d86)で修正しております。

2023-02-28 05:54 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        Date newFileDate = cl.getTime();
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/76ace57fd0a8f3d2ba179208a71592cf70b98815)で修正しております。

2023-02-28 05:55 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/3b1d82029a2c1d33454573fbbb2e3afa564015fb)で修正しております。

2023-02-28 05:55 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +                .append(rotatePolicy.getSettings())
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/99961f2f4d5acc7aa4cb915552bea004efe7ca8d)で修正しております。

2023-02-28 05:55 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        return "\tFILE AUTO CHANGE   = [" + true + "]" + Logger.LS;
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/99961f2f4d5acc7aa4cb915552bea004efe7ca8d)で修正しております。

2023-02-28 05:55 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        nextUpdateDate = cl.getTime();
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/d16c7d1290cb5c8094a18d9364453f2a3e8131c7)で修正しております。

2023-02-28 05:56 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        return !nextUpdateDate.after(currentDate);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/7b0dc78bc3d218a84c7b06df23930316036ab0cf)で修正しております。

2023-02-28 05:56 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> + * ファイルの最大サイズ以上になる場合は、ログのローテーションを行う。<br>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/0f0a32b581ab9fd9d229814af74433e62bd29de2)で修正しております。

2023-02-28 05:57 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +     * ファイルの最大サイズ以上になる場合は、ローテーションが必要と判定する。<br>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/93bf660b683e6581480ddded6e3d892920e34fc3)で修正しております。

2023-02-28 05:57 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +     * ローテーションが必要場合は、併せてローテーション実施時のリネーム先のファイルパスを更新する。<br>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/93bf660b683e6581480ddded6e3d892920e34fc3)で修正しております。

2023-02-28 05:57 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +        rotatePolicy.setupIfNeeded();
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/6a25a78f9f1c211a474b4e3070ac95130e018694)で修正しております。

2023-02-28 05:58 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/RotatePolicy.java
> +    void setupIfNeeded();
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/6a25a78f9f1c211a474b4e3070ac95130e018694)で修正しております。

2023-02-28 07:35 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/RotatePolicy.java
> +    void initialize(ObjectSettings settings, Charset charset);
インスタンス変数で保持する必要がなくなったので、[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/2443ef833f5efb3697a9a093d30f9a99151530e6)で削除しております。

2023-02-28 07:36 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * 日付ごとのローテーション判定に必要な日付を、dateTypeにsystemと設定されていればシステム日次から、
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/e7b648d15e3b30bf561e7367d28af1a6d7e220f1)で該当部分は削除しております。

2023-02-28 07:36 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            String currentDateSt = BusinessDateUtil.getDate();
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/e4c3fdd1a370dc1b9f3b175d773e5b1fef80f54b)でセグメント指定を追加しました。

2023-02-28 07:37 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            String currentDateSt = BusinessDateUtil.getDate();
また、業務日付の自動テストの際に一点不具合を見つけたので[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/b80c970e3838a747bb91e72d0ab9f9a9df7fd400)で修正しました。

2023-02-28 07:39 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +                .append(rotatePolicy.getSettings())
他の出力項目はSimpleClassNameではなく、ClassNameを出していたので[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/f1fbc1c25a061ef23277562a86dd73dfc9e3c1cb)で揃えました。

2023-02-28 07:41 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }};
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/86b17b9799d3abf0c1166e9d1ee901814d64dba6)で修正しました。

>変数の型はインタフェースで宣言しておくほうが良いです
こちらの修正対応がどのようにすべきか分からず、参考になるクラスなどあれば教えていただきたいです。

2023-02-28 07:43 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }};
また、自動テストについては以下のコミットも加えています。
[test: レビュー指摘修正による自動テストの修正](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/1be0d403d25fa714f9384bd9f5edb36d09ad2273)
[test: 自動テストを１メソッド１観点に修正](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/4f670f58b195a43b3570f3d7ad5a13bb7a08f216)
[test: 次回更新日付を初回ログ書き込み時に取得するようにした変更を自動テストに反映](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/ac621a2c3f1c5fac814efc9decc28ca49dced1b3)

2023-02-28 08:28 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * 日付ごとのローテーション判定に必要な日付を、dateTypeにsystemと設定されていればシステム日次から、
変更後でまた日次になっています。

2023-02-28 08:35 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +                .append(rotatePolicy.getSettings())
ROTATEとPOLICYは分けたほうがいいと思います。

2023-02-28 08:36 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        return "\tFILE AUTO CHANGE   = [" + true + "]" + Logger.LS;
セグメントを追加したのでそれも出すべきです。

2023-02-28 08:37 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        nextUpdateDate = cl.getTime();
decideRotatedFilePathのJavadocに次回ローテーション日を更新するという記述が残っています。

2023-02-28 08:46 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }};
> [こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/86b17b9799d3abf0c1166e9d1ee901814d64dba6)で修正しました。
> 
> > 変数の型はインタフェースで宣言しておくほうが良いです
> 
> こちらの修正対応がどのようにすべきか分からず、参考になるクラスなどあれば教えていただきたいです。

実装クラスの`FixedSystemTimeProvider`ではなく`SystemTimeProvider`で変数宣言する方がいいという意味です。
```
FixedSystemTimeProvider systemTimeProvider = new FixedSystemTimeProvider() {{
  setFixedDate("20161231235959999");
}};
```
ではなく
```
SystemTimeProvider systemTimeProvider = new FixedSystemTimeProvider() {{
  setFixedDate("20161231235959999");
}};
```

2023-02-28 11:48 UTC, kumagoro1202 requested changes

2023-02-28 11:48 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        expectedNextUpdateDate = cl.getTime();
178行目で宣言する意味は無いので宣言と代入を同時にしてください。

2023-02-28 11:48 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        assertThat(actualNextUpdateDate, is(expectedNextUpdateDate));
更新日時もコントロールした方がいいです。更新日時をコントロールすれば最初のFile.delete()もいらなくなります。
```java
    @Test
    public void testNextUpdateDateInInitialize() throws IOException {
        String logFilePath = "./log/testNextUpdateDateInInitialize-app.log";

        Calendar cl = Calendar.getInstance();
        cl.clear();
        cl.set(2023, Calendar.JANUARY, 1, 10, 30, 30);
        Date currentDate = cl.getTime();

        File f = new File(logFilePath);
        f.createNewFile();
        f.setLastModified(currentDate.getTime());

        Map<String, String> settings = new HashMap<String, String>();
        settings.put("appFile.filePath", logFilePath);
        settings.put("appFile.dateType", "system");

        DateRotatePolicy policy = new DateRotatePolicy();
        policy.initialize(new ObjectSettings(new MockLogSettings(settings), "appFile"));

        Date actualNextUpdateDate = Deencapsulation.getField(policy, "nextUpdateDate");

        // 次回更新予定日はファイル作成時刻の次の日
        cl.clear();
        cl.set(2023, Calendar.JANUARY, 2);
        Date expectedNextUpdateDate = cl.getTime();

        assertThat(actualNextUpdateDate, is(expectedNextUpdateDate));
    }
```

2023-02-28 11:48 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
SimpleDateFormatでパースするよりCalendarの方がわかりやすいかなと思いました。好みの問題かも知れません。
```java
        Calendar cl = Calendar.getInstance();
        cl.clear();
        cl.set(2023, Calendar.JANUARY, 1, 0, 0, 0);
        Date nextUpdateDate = cl.getTime();
```

2023-02-28 11:48 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        boolean actual = policy.needsRotate("abcdeabcde",Charset.forName(System.getProperty("file.encoding")));
```java
Charset.forName(System.getProperty("file.encoding"))
```
は以下と同じです。
```java
Charset.defaultCharset()
```

2023-02-28 11:48 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        boolean actual = policy.needsRotate("abcdeabcde",Charset.forName(System.getProperty("file.encoding")));
DateRotatePolicyではCharsetは使わないのであれば、インスタンス変数で`Charset.defaultCharset()`を保持してしまえば各テストメソッドで毎回取得する必要ないですね。
```java
    Charset ignored = Charset.defaultCharset();
    
    @Test
    public void testNeedsRotateIfNoNeeded() {
             ・
             ・
             ・
        boolean actual = policy.needsRotate("abcdeabcde", ignored);
             ・
             ・
             ・
    }
```

2023-02-28 11:48 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }
私ならこのテストはこう書くかなと思います。
```java
    Charset ignored = Charset.defaultCharset();

    /** 現在時刻<次回更新日の場合に、正しくrotateが必要かどうか判定を行えること */
    @Test
    public void testNeedsRotateIfNoNeeded() {
        Map<String, String> settings = new HashMap<String, String>();
        settings.put("appFile.filePath", "./log/dummy.log");
        settings.put("appFile.dateType", "system");

        DateRotatePolicy sut = new DateRotatePolicy();
        sut.initialize(new ObjectSettings(new MockLogSettings(settings), "appFile"));

        FixedSystemTimeProvider systemTimeProvider = SystemRepository.get("systemTimeProvider");
        systemTimeProvider.setFixedDate("20230101235959999");
        sut.setupAfterSystemRepositoryInitialized();

        // FixedSystemTimeProvider が固定日時を返すので必ず現在時刻<次回更新日となる。
        assertFalse(sut.needsRotate("message", ignored));
    }
```

Deencapsulationは奥の手だと思ってください。基本的には使わない。使わないでテストするにはどうすればいいか考えてください。考えても使わないといけないとなるようであれば設計に問題がある可能性があります。テストがしやすい設計になるよう考え直してください。

2023-02-28 11:48 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }
`FixedSystemTimeProvider`と`FixedBusinessDateProvider`はSystemRepositoryにloadはしておくけど、各テストメソッドで返す固定日付をsetするようにした方がわかりやすいです。setupでsetした日付を使うとテストメソッドを読む時にsetupで何を入れたかを覚えておかないといけないのでわかりにくいです。

2023-02-28 11:48 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
存在するかどうかだけが問題なので`exists()`の確認は要らないです。
`createNewFile()`はファイルがなければtrue、あればfalseを返すだけで既にあってもエラーにはならないので
```java
    @Test
    public void testDecideDupRotatedFilePath() throws IOException {
        File f = new File("./log/app.log");
        if (f.exists()) {
            f.delete();
        }
        File dupf = new File("./log/app.log.20161230.old");
        dupf.createNewFile();     
```
でやりたいことはできるかと思います。

2023-02-28 11:48 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }
リテラルでfilePathを書いているとどれとどれが同じものを指しているかがわかりにくいです。なるべく変数を使いましょう。
```java
    @Test
    public void testRotate() throws IOException {
        String currentFilePath = "./log/testDateRotate-app.log";
        String rotatedFilePath = "./log/testDateRotate-app.log.old";
        
        Map<String, String> settings = new HashMap<String, String>();
        settings.put("appFile.filePath", currentFilePath);
        settings.put("appFile.dateType", "system");

        DateRotatePolicy policy = new DateRotatePolicy();
        policy.initialize(new ObjectSettings(new MockLogSettings(settings), "appFile"));

        File f = new File(currentFilePath);
        f.createNewFile();
        
        File expected = new File(rotatedFilePath);
        if (expected.exists()) {
            expected.delete();
        }

        policy.rotate(rotatedFilePath);

        if (!expected.exists()) {
            fail();
        }
    }
```

2023-02-28 11:48 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +import java.util.Date;
`FileLogWriterTest`からは`FileSizeRotatePolicy`に関するテストは削除してください。例えば`testMaxFileSizeLeZero`は`FileSizeRotatePolicy`に値を設定するもので`FileSizeRotatePolicy`の実装に依存しています。このようなテストはなくし、`RotatePolicy`をモック化して`FileLogWriter`の`initialize`が呼ばれたら`RotatePolicy`の`initialize`が想定した引数で呼び出されることを確認するようなテストを作ってください。

2023-02-28 11:55 UTC, kumagoro1202 requested changes

2023-02-28 11:55 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +    /** システム日付のローテーションでファイルが自動で切り替わること。*/
`FileLogWriterTest`からは`DateRotatePolicy`や`FileSizeRotatePolicy`に関するテストは削除してください。このようなテストはなくし、`RotatePolicy`をモック化して`FileLogWriter`の`initialize`が呼ばれたら`RotatePolicy`の`initialize`が想定した引数で呼び出されることを確認するようなテストを作ってください。
このテストで確認しているようなローテーションされる条件は`RotatePolicy`の実装クラスが責任を持つことです。testSwitchedとtestSystemDateSwitchedとtestBusinessDateSwitchedのように`RotatePolicy`の実装クラスに依存したテスト観点は実装クラスの単体テストでやるべきことです。FileLogWriterの責務はローテーションされた場合にきちんと新しいファイルにログを出力できることなのでその観点だけ確認すればよいです。

2023-03-01 07:43 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * 日付ごとのローテーション判定に必要な日付を、dateTypeにsystemと設定されていればシステム日次から、
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/55cfb47429d39f180b7b793d0b962665242c4aaf)で日付タイプなどの指定はなくなっています。

2023-03-01 07:51 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        return "\tFILE AUTO CHANGE   = [" + true + "]" + Logger.LS;
日付タイプの指定はなくなったので取り下げをお願いします。

2023-03-01 07:52 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        nextUpdateDate = cl.getTime();
すみません。確認漏れでした。
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/55cfb47429d39f180b7b793d0b962665242c4aaf#diff-9aa96aac354607dc8e9f905606ef24d10beb105f542bda43d8589986921d8cc6L152)で修正しております。

2023-03-01 07:54 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }};
理解しました。

2023-03-01 07:54 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }};
Java Dateクラスでの時間取得になったのでFixedSystemTimeProvider自体は使用しなくなりました。

2023-03-01 07:57 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        expectedNextUpdateDate = cl.getTime();
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/c8fd75a8490a3915c2bc58fd042da04fb2590fb9#diff-679a0e3d9e1e549676f9a11b8335a58ea59ce958efd985f40591d54646a54b8dL176-L188)で無駄な宣言をなくしました。
クラス全体を確認済みです。

2023-03-01 07:59 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        assertThat(actualNextUpdateDate, is(expectedNextUpdateDate));
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/c8fd75a8490a3915c2bc58fd042da04fb2590fb9#diff-679a0e3d9e1e549676f9a11b8335a58ea59ce958efd985f40591d54646a54b8dL156-L159)でFileDeleteなども削除し、
更新日時もプログラム上で設定するように修正を加えました。

2023-03-01 08:00 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
一例としては[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/c8fd75a8490a3915c2bc58fd042da04fb2590fb9#diff-679a0e3d9e1e549676f9a11b8335a58ea59ce958efd985f40591d54646a54b8dL204)でSimpleDateFormatを使用しなくしました。
クラスを全体的に見直しております。

2023-03-01 08:02 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        boolean actual = policy.needsRotate("abcdeabcde",Charset.forName(System.getProperty("file.encoding")));
一例として[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/c8fd75a8490a3915c2bc58fd042da04fb2590fb9#diff-679a0e3d9e1e549676f9a11b8335a58ea59ce958efd985f40591d54646a54b8dL212)でインスタンス変数を利用するようにしました。
クラス全体を見直しております。

2023-03-01 08:04 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/c8fd75a8490a3915c2bc58fd042da04fb2590fb9#diff-679a0e3d9e1e549676f9a11b8335a58ea59ce958efd985f40591d54646a54b8dL211)で修正しております。
DateRotePolicyTest内ではDeencapsulation.setFieldを一切使わないようにしました。
また、固定日付のSETも各メソッドごとで実施するように修正を加えております。

2023-03-01 08:05 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/a6e85240804483fa5c5bb5dbd60ba306c9d1eeca)でFileSizeRotatePolicyTestにも同様の修正を加えております。

2023-03-01 08:12 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/c8fd75a8490a3915c2bc58fd042da04fb2590fb9#diff-679a0e3d9e1e549676f9a11b8335a58ea59ce958efd985f40591d54646a54b8dL331-L338)で修正しております。
クラス全体を見直しています。

2023-03-01 08:13 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
一件修正漏れがあったので、[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/fa9c81ed88c8b4e3acf17dfc453b628c90be12df)で修正しております。

2023-03-01 08:14 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }
一例として[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/c8fd75a8490a3915c2bc58fd042da04fb2590fb9#diff-679a0e3d9e1e549676f9a11b8335a58ea59ce958efd985f40591d54646a54b8dL371)で修正しております。
クラス全体を見直しております。

2023-03-01 10:17 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/d63025356a6f9292ee11e47e3fdb69f3f4d1daf0)でgetFieldも一切使わないようにしました。

2023-03-01 10:29 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +                .append(rotatePolicy.getSettings())
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/e1352c1e185372d33d96a70e997ae169e9d44e05)で修正しました。

2023-03-01 10:49 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +    /** システム日付のローテーションでファイルが自動で切り替わること。*/
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/f142cbf82ee3ecfba0a303a719d2a7fa25990602)でRotatePolicyの実装クラスに依存するテストは削除しました。

>testSwitchedとtestSystemDateSwitchedとtestBusinessDateSwitchedのようにRotatePolicyの実装クラスに依存したテスト観点は実装クラスの単体テストでやるべきことです

DateRotatePolicyTestのtestDecideDupRotatedFilePathで担保できています。

>FileLogWriterの責務はローテーションされた場合にきちんと新しいファイルにログを出力できることなのでその観点だけ確認すればよいです

FileLogWriterTestのtestSwitchedで担保できています。

2023-03-02 04:17 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +    /** システム日付のローテーションでファイルが自動で切り替わること。*/
[RotatePolicy](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/cb80d064d76e55b01f2bd46952c5a8390d94a9c1)をモック化したテストはこちらで追加しております。

2023-03-02 04:59 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * 日付ごとのローテーション判定に必要な日付を、dateTypeにsystemと設定されていればシステム日次から、
Dailyという意味で日次だと言っているなら違うと思います。
日次でローテーションを行うクラスと言われると、日付を監視して日付が変わるタイミングでローテーションするようなクラスをイメージします。
このクラスは日次とは限らず、ログを書き込むタイミングで日時をチェックし、予め設定した切り替え日時を超えていたらローテーションするというクラスなので、日時によるログのローテーションとするべきかと思います。
また、`日次`に対して`による`と続くのも日本語として違和感があります。日次でローテーションを行う、日毎にローテーションを行う、などは違和感がありません。
クラス名もDailyRotatePolicyではなくDateRotatePolicyにしているので、「日時」とするのが正しいと思います。

2023-03-02 05:03 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +                .append(rotatePolicy.getSettings())
JavadocがROTATEPOLICYのままです。

2023-03-02 05:04 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        return "\tFILE AUTO CHANGE   = [" + true + "]" + Logger.LS;
取り下げ

2023-03-02 09:28 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * 日付ごとのローテーション判定に必要な日付を、dateTypeにsystemと設定されていればシステム日次から、
厳密に意味を考えると確かに、日時の方があっていますね。
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/54f5645915cad17f2cc1c9767aa1de064b550840)で、「日次による」→「日時で」に修正を加えました。

2023-03-02 09:29 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> +                .append(rotatePolicy.getSettings())
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/b6df7f247c0a12b88813514612cbff238aeb3328)でJavadocを修正しました。
また、ROTATEとPOLICYは分けたことによってFileLogWriterを継承しているクラスでのテストが失敗するようになっていたので[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/1e38ee57e4ee67a55dbee5eb205613b55418b075)で修正しました。

2023-03-02 10:16 UTC, opengl-8080 requested changes

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * </dl>
分以下で指定したくなったときに新規クラスを作るしかないため汎用性が低いかなと思いました。

以下、直接話し合って決まった仕様。

- 時分秒までの単位で切り替えの時間を指定できるようにする
- `HH`, `HH:mm`, `HH:mm:ss` のいずれかのフォーマットで指定できるようにする

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private final DateFormat dupFileDateFormat = new SimpleDateFormat("yyyyMMddHHmmssSSS");
`SimpleDateFormat` はスレッドセーフではないので、インスタンス変数に保存して使いまわすのはやめておきましょう。
日付のフォーマットを`String` の定数で定義しておいて、利用時に都度 `SimpleDateFormat` を new するようにしましょう。

参考:[SimpleDateFormatはスレッドセーフではない - Qiita](https://qiita.com/kazuy/items/5463bbcd0aea906b8820)

元の実装では `SimpleDateFormat` を唯一使っている `renameFile` が `synchronized` で実行されているので同期がなんとか取れていました。
しかし、今回クラスが分かれたことで「本当に同期が取れているか？」の確認がより困難になりました（利用しているクラスを特定し、マルチスレッドで呼ばれるパスが存在するか読み解く必要がある）。
`SimpleDateFormat` を使いまわしていると「これは本当に同期がとられているのか？」とわざわざ確認する手間が発生するので、余計なことを考えないで済むように使うたびに毎回 new しておくのが良いと思います。

（個人的には、元の実装の時点でも `SimpleDateFormat` を使いまわすのはよくないと思ってます）

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        File file = new File(filePath);
変数宣言は、その変数を利用している場所の近くでするようにしましょう。

変数の宣言と利用箇所が離れると、その変数がどう使われているのかが分かりにくくなっていきます。
どう使われているかが分かりにくくなると、その変数に変更を加えたときの影響範囲が分かりにくくなります。
すると、修正がしづらいコードになります。

変数の宣言と利用箇所が近くにまとまっていると、その変数に変更を加えたときの影響範囲が分かりやすくなり、修正しやすいコードになります。

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            currentDate = new Date(file.lastModified());
Javadoc を見ると、 `lastModified` は入出力エラーのときに 0L を返すそうです。

> ファイルが存在しないか、入出力エラーが発生した場合は0L
https://docs.oracle.com/javase/jp/8/docs/api/java/io/File.html#lastModified--

0L が返された場合の処理も書いておいた方がいいのではないかと思いました。
エラーとするのか `new Date()` 扱いにするかは要検討。

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +     * 現在時刻 > インスタンス変数として保持している次回ローテション時刻の場合、ローテーションが必要と判定する。<br>
「現在時刻 > インスタンス変数として保持している次回ローテション時刻」ではなく、
「現在時刻  ≧ インスタンス変数として保持している次回ローテション時刻」ではないでしょうか？

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private String filePath;
`filePath` だけだと何のファイルなのか分かりにくいと感じたので、 `logFilePath` とかにしましょう。

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +     *
`{@code [<次回更新時刻>]}` のように書けばエスケープは不要になると思います。

FileLogWirter の書き方を真似たのだと思いますが、せっかく新しく作られるクラスなのでシンプルな書き方ができるこちらにしておきましょう。

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + *     デフォルト値は{@link FileSizeRotatePolicy}<br>
クラスの完全修飾名を指定することを説明したほうがいいと思いました。

また、「デフォルト値は FileSizeRotatePolicy 」となっていますが、このプロパティで指定される値という意味では `nablarch.core.log.basic.FileSizeRotatePolicy` になるので「デフォルト値は FileSizeRotatePolicy 」という説明に違和感を覚えました。

「デフォルト値は nablarch.core.log.basic.FileSizeRotatePolicy」か「デフォルトでは FileSizeRotatePolicy が使用される」とかなら違和感ないと思いました。

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> + *     このオプションは、rotatePolicyに{@link FileSizeRotatePolicy}が設定されているか、何も設定されていない場合に有効である。</dd>
> このオプションは、rotatePolicyに{@link FileSizeRotatePolicy}が設定されているか、何も設定されていない場合に有効である。

この説明は要らないのではと思いました。

rotatePolicy に何も設定されていない場合は FileLogWirter の Javadoc で FileSizeRotatePolicy がデフォルトで利用されると書いてあるので、 FileSizeRotatePolicy が指定された場合と同じ扱いということになるからです。

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +    private final DateFormat oldFileDateFormat = new SimpleDateFormat("yyyyMMddHHmmssSSS");
`DateRotatePolicy` の指摘と同じく、 `SimpleDateFormat` を使いまわすのはやめておきましょう。

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +    private String filePath;
`DateRotatePolicy` の指摘と同じく、 `logFilePath` にしましょう。

2023-03-02 10:16 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +     * CURRENT FILE SIZE  = [&lt;書き込み先ファイルの現在のサイズ&gt;]<br>
`DateRotatePolicy` の指摘同様、 `{@code}` を使った書き方にしましょう。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }
`System` をモック化するのはリスクがでかいのでやめておきましょう。
（`System` はライブラリ含め様々な処理で利用されている可能性が高く、モック化するとそれら `System` を利用している箇所の動きに影響を与えてしまう恐れがあるため）

`new Date()` しているところを `protected` メソッドに切り出して、テストでオーバーライドするようにしましょう。
まだそちらの方がリスクは小さくなると思います。

```java
public class DateRotatePolicy {
  protected Date currentDate() {
    return new Date();
  }
}
```

```java
public class DateRotatePolicyTest {

  @Override
  public void testNeedsRotateIfNoNeeded() {
    ...
    DateRotatePolicy policy = new DateRotatePolicyForTest(fixedDate);
    ...
  }

  private static class DateRotatePolicyForTest extends DateRotatePolicy {
    private Date currentDate;

    public DateRotatePolicyForTest(Date currentDate) {
        this.currentDate = currentDate;
    }

    @Override
    protected Date currentDate() {
      // 固定日を返すように実装
    }
    private void setCurrentDate(Date currentDate) {
      this.currentDate = currentDate;
    }
  }
}
```

もっときれい？にするなら、日付を取得する処理をインタフェースで切って別クラスに分けてテスト時に差し替えるとかすることになりますが、さすがにオーバーエンジニアリングだと思うのでこれくらいの方法が落としどころだと思います。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        dateTimeMock = new DateTimeMock(cl.getTime());
```java
public void testNeedsRotateIfNoNeeded() {
  Date currentDate = date("2018-01-01 10:10:10.000");
  ...
}

private Date date(String textDate) {
  // 日付をパースして Date にして返す処理
}
```

こんな感じで、視覚的に分かりやすい形で日付を生成できるメソッドを作りましょう。
日付や時刻は `cl.set(2018, Calendar.JANUARY, 1, 10, 10, 10)` のようなプログラム的な記述よりも、 `2018-01-01 10:10:10` のような日常的に慣れ親しんだ表記の方が人間が理解しやすいです。
テストコードはただでさえ読むのが大変なので、できるだけ雑音を減らして人間が読みやすい形にしたほうがいいです。

なお境界値のテストができるように、ミリ秒まで指定できるほうがいいと思います(`Date` の精度はミリ秒なので)。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        policy.initialize(new ObjectSettings(new MockLogSettings(settings), "appFile"));
ログファイルの名前を全テストケースで共通にすれば、この部分（既存ファイルの削除～`ObjectSettings`の準備）は `@Before` にまとめられるのではないでしょうか？

そうすれば、各テストメソッドの中の実装量が減ってテストメソッドの中の見通しが良くなります（何をしているかが把握しやすくなり、保守しやすくなる）。

ログファイルを分けることで全テスト実行後にそれぞれのテストでのログを確認できるという意図があるのかなと思いましたが、それよりもテストメソッドが読みやすくなるメリットの方が大きいと思いました。
テストメソッドは往々にして複雑でややこしくなりやすいので、少しでも簡潔にして保守しやすくしておくべきだと思います。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        cl.clear();
冒頭の日付を生成するメソッドの対応を入れるとこの部分は無くなると思いますが、一応気になったので指摘しておきます。

基本的に、変数の使いまわしはすべきではありません。
理由は、ソースが読みにくくなり、修正がしづらくなるからです。
変数を使いまわすと、その変数がどこからどこまではどういう目的で使われているか、どこで改めて初期化されたのかを正確に把握する必要性が生じます。
そうしないと、将来そのソースを修正するときに「この変数をこの場所で修正すると、どの部分に影響があるか？」が分からないためです。
ループなどが絡むと、それは非常に難しくなります。

目的が異なるのであれば、その都度異なる名前の変数を定義して、限られた狭いスコープで変数を利用するようにしましょう。
スコープが狭い変数は、どう利用されているかを簡単に読み解くことができます。
すると、その変数に手をいれたときの影響範囲が簡単に限定でき、安心してソースを修正しやすくなります。

例外としては、その変数の初期化が非常に高コストで何回も実行していると処理速度に影響を及ぼすようなケースですが、そのようなケースは基本的に遭遇することはないです(組み込みサーバーの起動とかファイル・DBの入出力など)。
なのでまずは、変数は再利用しない、というスタイルでソースをとりあえず書いて、もし実行してみて遅くて問題になったらそのとき修正する、というやり方でいいと思います。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }
境界値テストがあった方が良いと思いました。

- 現在日時 = 次回ローテーション日時 - 1ms
- 現在日時 = 次回ローテーション日時
- 現在日時 = 次回ローテーション日時 + 1ms

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        String rotatedFilePath = "./log/testDecideDupRotatedFilePath-app.log.201801010000.old";
変数で定義しなくても、 `new File()` の引数に直接渡せばいいのでは？と思いました。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        f.createNewFile();
`f` だと何の変数か分かりにくいので、ちゃんと名前をつけましょう。
(他も同様)

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
これも `@Before` で消すようにすれば、わざわざテストケースの中で書く必要がなくなると思います。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
リネームされていることをテストするとなると、リネーム前のファイルが無くなっていることも確認しないといけないと思いました。

`rotate` の前後で、次のような感じのアサーションをするようにしましょう。

- `rotate` 前
  - リネーム前のファイルが存在すること
  - リネーム後のファイルが存在しないこと
- `rotate` 後
  - リネーム前のファイルが存在しないこと
  - リネーム後のファイルが存在すること

アサーションは、他が Hamcrest の API を使っているのに合わせて、次のような感じで書きましょう。

```java
assertThat(expectedFile.exists(), is(true));
```

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    @Test(expected = IllegalStateException.class)
これだと例外の型しか判定できず、本当に意図した例外かわかりません。
（実は全然関係ない `IllegalStateException` がスローされていたとしても、テストが通ってしまう）

例のテストは、 `assertThrows` を使いましょう。
スローされた実際の例外オブジェクトを取得できるので、メッセージの検証などができます。

```java
        IllegalStateException exception = assertThrows(IllegalStateException.class, new ThrowingRunnable() {
            @Override
            public void run() throws Throwable {
                policy.rotate(expectedPath);
            }
        });
        assertThat(exception.getMessage(), is("..."));
```

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        };
`Expectations` はモックオブジェクトにダミーの動きを記録するためのものだったと思うので、この記述は不要ではないでしょうか？
呼び出されているかどうかは↓の `VerificationsInOrder` でチェックしているので、ここの `Expectations` はなくてもいいと思いました。

他も、消しても動く分については消しておきましょう。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        };
`rotate` が呼ばれていないことの確認が必要ではないでしょうか？

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +
全体的に、 `DateRotatePolicyTest` での指摘同様に、ログファイル名を同じにすることで `@Before` にまとめられる処理はなるべくまとめましょう。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        }
`DateRotatePolicyTest` の指摘と同じく、 `rotate` 前後でアサートしてリネームされていることを検証しましょう。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +    @Test(expected = IllegalStateException.class)
`assertThrows` を使いましょう。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +     *  maxFileSizeが0KBのためfalseを返す */
Javadoc のコメントの終端(`*/`)が変なところにあります。
複数行の場合の Javadoc コメントとして一般的な体裁と異なっているので、修正しましょう。

他にも Javadoc のコメントとして不自然な体裁のものは見直してください。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +    }
`if (maxFileSize <= 0) {` で判定しているので、 `maxFileSize` が負数の場合もテストすべきだと思いました。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +    }
ランダムな文字列である必要はないのでは？と思いました。
仮に文字種のテストをしたいのであれば、それこそランダムではなく固定された文字種でテストすべきですし。

あと、 `get*` というメソッドは Java Beans の Getter メソッドを彷彿とさせるので、別の動詞の方がいいと思いました。

↓のファイル出力への指摘に修正案載せてます。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        filewriter.close();
指定されたサイズのファイルを生成するユーティリティメソッドに切り出しましょう。

```java
    private File newFile(String path, int byteSize) {
        String content = generateZeroPaddingString(byteSize);
        
        FileWriter fileWriter = null;
        try {
            fileWriter = new FileWriter(path);
            fileWriter.write(content);
        } catch (IOException e) {
            throw new RuntimeException(e);
        } finally {
            FileUtil.closeQuietly(fileWriter);
        }
        
        return new File(path);
    }
    
    private String generateZeroPaddingString(int byteSize) {
        char[] content = new char[byteSize];
        Arrays.fill(content, '0');
        return new String(content);
    }
```

また、ファイルなどの入出力ストリームの `close` は確実に解放されるように `finally` 句で書きましょう。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +     *  maxFileSizeが20バイトだが、currentFileSizeが15バイトでmsgLengthが10バイト */
単位 KB ではないですか？
他も同様。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        String str = getAlphaNumericString(10 * 1000);
10KB の計算が 10 * 1000 になっていますが、 1KB は 1024byte なので正しくは 10 * 1024 です。
他も同様。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +    }
境界値テストとなるようなパターンで検証しましょう。

`maxFileSize` が 20KB、ファイルサイズが 19KB で、

- メッセージが 1023 byte ならローテーションしない
- メッセージが 1024 byte ならローテーションする
- メッセージが 1025 byte ならローテーションする

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +     *  maxFileSizeが20バイトだが、currentFileSizeが15バイトでmsgLengthが10バイト */
`testNeedsRotateIfNotNeeded` のコメントに書いている「rotate不要」のように、期待される結果も書いた方がいいと思いました。
「正しく」判定が行われているかどうかは仕様を知らないと分からないので。
他も同様。

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        assertTrue(actual.startsWith("./log/app.log.") && actual.endsWith(".old"));
Hamcrest を使えば以下のように書けます。

```java
        assertThat(actual, allOf(
            startsWith("./log/app.log."),
            endsWith(".old")
        ));
```

検証エラーだったときのメッセージがこちらのほうが分かりやすく出るので、こちらの方が好ましいです。

```
java.lang.AssertionError: 
Expected: (a string starting with "./log/app.log." and a string ending with ".old")
     but: a string starting with "./log/app.log." was "./log/app.logxxx.20230302190439479.old"
```

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        oldFileDateFormat.parse(oldDate);
一見すると JUnit のアサートがないため、何をやっているのか分からず混乱しました。

おそらく、ファイル名の日付を出力している部分をパースしてエラーにならないことで「日付がフォーマットされて出力されている」ことを確認しようとしているのだと理解しました。

何の説明もないと、これに気づくのに時間がかかります。
将来このコードを読む人たちのために、コメントでこのコードの意図を残してください。

あと、デフォルトは厳密な検査が行われないと思うので、 `setLenient` で `false` を設定しておいた方がいいと思いました。

https://docs.oracle.com/javase/jp/8/docs/api/java/text/DateFormat.html#setLenient-boolean-

2023-03-02 10:16 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +                + "\tCURRENT FILE SIZE   = [" + 5L + "]" + Logger.LS;
`20L > 0L`, `20000L`, `5L`

この3つは固定値なので文字列連結する必要はないのでは？と思いました。

2023-03-02 11:02 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * 日付ごとのローテーション判定に必要な日付を、dateTypeにsystemと設定されていればシステム日次から、
日時であれば「日時による」でも問題ないと思います。

2023-03-03 00:08 UTC, opengl-8080 requested changes

2023-03-03 00:08 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + *     時刻は24時間表記とする。デフォルトは0。</dd>
`updateTime` の説明は変更する必要があると思います。

2023-03-03 00:08 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            } else {
上の if ブロックは `throw` で処理を中断しているので、 `else` にする必要はないと思いました。
ネストは深くするとそれだけ読みにくくなるので、少しでもネストは減らした方がいいと思います。

2023-03-03 00:08 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +                    }
`SimpleDateFormat` でパースしましょう。
日付としての正確性の検証も `SimpleDateFormat` に任せることができるので、そちらの方が確実で安全だと思います。

`HH` や `HH:mm` で設定されたときは末尾に `:00` などを補完してパースできるようにするイメージです。

```java
SimpleDateFormat format = new SimpleDateFormat(UPDATE_TIME_FORMAT);
format.setLenient(false);
try {
    updateTime = format.parse(textUpdateTime);
} catch (ParseException e) {
    throw new IllegalArgumentException("Invalid updateTime", e);
}
```

あと、時分秒で分けて保存しないで、 `Date` で保存しておけばいいと思いました。
`calcNextUpdateDate` で時分秒それぞれで set する必要がなくなるので。

2023-03-03 00:08 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +                    throw  new IllegalArgumentException("Invalid updateTime");
例外を catch して別の例外をスローする場合は、 catch した例外をスローする例外に設定するようにしましょう。
そうしないと、スタックトレースの caused by が出力されなくなります。
caused by が出力されないと、 catch した例外がスローされた原因が特定できず、障害発生時に原因調査が難しくなります。

```java
throw new IllegalArgumentException("Invalid updateTime", e);
```

2023-03-03 00:08 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    @Ignore
この `@Ignore` は必要ないように思いました。

2023-03-03 00:08 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        private int seconds;    // 秒
別のところで指摘している、「日付の生成を二元が見やすい形にする」と「共通処理を `@Before` にまとめる」の話を実施するとたぶんこの持ち方も変えざるを得ないと思うので、合わせて見直しお願いします。
（というか、全部同じ値だから、そもそもパラメータにする必要が無いような？）

2023-03-03 00:08 UTC, opengl-8080 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
例外のアサートは `assertThrows` を使いましょう。

2023-03-03 00:14 UTC, opengl-8080 commented
ブランチ名が NBA になってます（正しくは NAB）。
ブランチ名が間違っていると JIRA との連携がうまくいかない可能性があるので、修正しておいてください。

2023-03-03 00:46 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            currentDate = new Date(file.lastModified());
ここでのfileは書き込み先のファイルです。
ログの書き込み時などに、例外がでるよりかは起動時に例外を出してしまった方がいい気がしました。
例）IllegalStateException("failed to read. file name = ****")

2023-03-03 08:34 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * </dl>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/5f9988ae45cf022cb92ca7a7cce74107fb4f4d6d)で記載を修正しております。

2023-03-03 08:35 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private final DateFormat dupFileDateFormat = new SimpleDateFormat("yyyyMMddHHmmssSSS");
意図については理解しました。
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/b28d995184a6c17deb7d8406f53d29eb5bf0482a)で毎回newするように修正しました。

2023-03-03 08:36 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        File file = new File(filePath);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/3e81eab147a5c6e061fb70c4cdcf0065f8a0c2d4)で修正しました。

2023-03-03 08:37 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +     * 現在時刻 > インスタンス変数として保持している次回ローテション時刻の場合、ローテーションが必要と判定する。<br>
ご指摘の通りです。[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/30fb67844e12498fe3c8344e6beb60a8574bd4fd)で修正しております。

2023-03-03 08:38 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private String filePath;
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/1aca4a4873a5f797ec12a8cf1b690db4d1a80b04)で修正しました。
File fileなども、File logFileなどの記載に修正しました。

2023-03-03 08:39 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +     *
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/b845ef2888e9e8f22c692f2b3f5651cf2d2596d4)で修正しております。

2023-03-03 08:40 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileLogWriter.java
> + *     デフォルト値は{@link FileSizeRotatePolicy}<br>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/44190575bf7f5791ff543b6ba548b311cf7bcd49)で修正しました。
解説書内で、**完全修飾名**よりかは**FQCN**という言葉の方が使われていたのでそのようにしています。

2023-03-03 08:41 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> + *     このオプションは、rotatePolicyに{@link FileSizeRotatePolicy}が設定されているか、何も設定されていない場合に有効である。</dd>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/38b41820ed14efd7feef8ddf3a3bbeeae182b843)で修正しております。

2023-03-03 08:41 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +    private final DateFormat oldFileDateFormat = new SimpleDateFormat("yyyyMMddHHmmssSSS");
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/57deb3cf5e32566c2d2bbfff817b850a42575296)で修正しております。

2023-03-03 08:42 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +    private String filePath;
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/af98933e65df74b05723b73d9122b8a4c68026fa)で修正しております。

2023-03-03 08:42 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +     * CURRENT FILE SIZE  = [&lt;書き込み先ファイルの現在のサイズ&gt;]<br>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/20605180a6bd1391b996a99a175339566912c136)で修正しております。

2023-03-03 08:45 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }
new Date()をメソッドに分けて、オーバライドする..その発想はなかったです。

[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/c2543cb876cb1cd614206c238d18b2b8e0f9fb78)で反映しました。

2023-03-03 08:48 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        policy.initialize(new ObjectSettings(new MockLogSettings(settings), "appFile"));
元々Before記載していた、テスト失敗していたのでやめてました。
おそらくファイル名を共通でapp.logにしていたので他のクラスのテストが影響していたんだと思います。
ファイル名をクラス特有のものにしたら通りました。

[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/3d2193ff706966011ed8231f1db197e4fb11747f)で修正しました。

2023-03-03 08:49 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        cl.clear();
>変数は再利用しない、というスタイルでソースをとりあえず書いて

肝に銘じておきます。

2023-03-03 08:51 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        f.createNewFile();
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/064ad27845c3a84f6aba6351f9fb26b165322130)で修正しました。

2023-03-03 08:51 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/45e3b75722d7f502bcec720be9b90e74f82d7207)でリネーム時の確認事項を追加しています。

2023-03-03 08:52 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    @Test(expected = IllegalStateException.class)
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/7a1dc6f1c913ee1af9955662b93f418000af9df4)でassertThrowsを使うようにしました。

2023-03-03 08:52 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        };
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/8f57600f442d549132bef14795251b054519a89b)で不要なExpectations内の定義を削除しました。

2023-03-03 08:53 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/3d2193ff706966011ed8231f1db197e4fb11747f)でまとめております。

2023-03-03 08:54 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        }
[こちら](nablarch-core-applog/pull/17/commits/167a95d9d6c274894fe696b1f14c2c26d7d97d92)で確認項目を追加しています。

2023-03-03 08:54 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +    @Test(expected = IllegalStateException.class)
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/b7c2861b4bc9fcf214730bb919aa577ac04ce4c1)でassertThrowsを使うようにしました。

2023-03-03 08:55 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +     *  maxFileSizeが0KBのためfalseを返す */
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/30e7d63ec6b476038528fd40a55b9d134ab11622)で修正しております。

2023-03-03 08:56 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +    }
対処した内容については↓で記載しています。

2023-03-03 08:56 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        filewriter.close();
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/ba1193e732c7686798ed943551bdfa88a8053922)で反映しました。

2023-03-03 08:58 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +     *  maxFileSizeが20バイトだが、currentFileSizeが15バイトでmsgLengthが10バイト */
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1122791689)の対応中に修正済みです。

2023-03-03 08:58 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +     *  maxFileSizeが20バイトだが、currentFileSizeが15バイトでmsgLengthが10バイト */
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1122791689)の対応で修正済みです。

2023-03-03 09:01 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        assertTrue(actual.startsWith("./log/app.log.") && actual.endsWith(".old"));
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/43c7fe76d66bdd6d0f572c563f4c9ef3f78a9ffc)で反映しました。
マッチルールなどのテストの際には使うようにしてみます。

2023-03-03 09:01 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        oldFileDateFormat.parse(oldDate);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/50f428aa72632385fa881ca8dc068a1ada54ab95)で説明の追記と厳密な検査を行うような修正をしております。

2023-03-03 09:02 UTC, tacitusxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +                + "\tCURRENT FILE SIZE   = [" + 5L + "]" + Logger.LS;
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/c119e903b5362c6436bd3fcbaad4197408b73700)で対応しました。

2023-03-03 09:03 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            } else {
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/1d81c40b54b0d3f0c8a35f48a72dbe974d749432)で対応しております。
下ふたつの指摘についてもこちらのコミットで対応しております。

2023-03-03 09:03 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +                    }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1123868885)のレビュー指摘内の修正で対処しております。

2023-03-03 09:03 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +                    throw  new IllegalArgumentException("Invalid updateTime");
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1123868885)のレビュー指摘内の修正で対処しております。

2023-03-03 09:04 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    @Ignore
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/6dd3d0943af44ae989c8e2dd9a6ecfba75cc72c5)で削除しました。

2023-03-03 09:04 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/414af82213a9ff9bed97d33d3a4ac925ca255341)で対処しました。

2023-03-03 09:10 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + *     時刻は24時間表記とする。デフォルトは0。</dd>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1122599579)のレビュー指摘で対応しております。

2023-03-03 09:20 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        dateTimeMock = new DateTimeMock(cl.getTime());
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/848c2b2cd9e184d11fe961279cf4c1d7069765dc)で、Calenderオブジェクトは完全に使わないようにしました。
ミリ秒対応は次のコミットで実施します。

2023-03-03 09:30 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        cl.clear();
該当部分は、[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1122651207)のレビュー指摘対応でなくなっています。

2023-03-03 09:34 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        String rotatedFilePath = "./log/testDecideDupRotatedFilePath-app.log.201801010000.old";
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/345790d0839a8ad055f54f64c095795c9db03a8d)で修正しております。

2023-03-03 09:37 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
該当部分は[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1122664324)のレビュー指摘で亡くなっております。

2023-03-03 09:49 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        private int seconds;    // 秒
該当部分は、[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1122651207)のレビュー指摘対応でなくなっています。

2023-03-03 10:20 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +            currentDate = new Date(file.lastModified());
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/134bc75cc45d9f0bf76ca1e084feec8ec1322130)で処理を追加しました。

2023-03-03 10:22 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        };
`needsRotate`でfalseが返されるので、rotateは呼ばれないです。

2023-03-06 02:07 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        String str = getAlphaNumericString(10 * 1000);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/bb80ec5cc29ee640bfc4e2f3e991eb7a6cafab97)で修正しました。
他の項目は境界値テストに使用するものです。
[FileLogWriter](https://nablarch.github.io/docs/5u8/javadoc/nablarch/core/log/basic/FileLogWriter.html)の仕様上
1000Bを1KB換算するため、境界値テストの項目には適用できません。

2023-03-06 02:09 UTC, tacitusxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +    }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/142a803b3180981019ea213480e9d6ab5856fe46)で修正しました。
[FileLogWriter](https://nablarch.github.io/docs/5u8/javadoc/nablarch/core/log/basic/FileLogWriter.html)の仕様上
1000Bを1KB換算するため、上のケースの場合メッセージの境界値は1000 byte なのかと思います。

2023-03-06 02:10 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +    }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/cd0e1e62fd01114010e2d5e86c949757a032be90)で修正しました。

2023-03-06 02:11 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/1bbeae9d9d84c9dafdab93877251458a38546e7e)で対応しております。

2023-03-06 04:55 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * </dl>
> 特定の時刻以降の

ローテーションはある単一のタイミングで行うものなので違和感があります。
「特定の時刻にログファイルをローテーションしたい場合」の方がいいと思います。

> デフォルトは0

こちらもHHとして解釈して0時になると言いたいんだというのは理解できますが、「00:00:00」としてあげたほうが利用者がぱっと理解しやすいかなと思います。

2023-03-06 05:29 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        f.createNewFile();
fのものがまだ残っています。testInvalidRotate、testGetSetting

2023-03-06 05:33 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
なくなっていないように見えます。

2023-03-06 05:34 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
> アサーションは、他が Hamcrest の API を使っているのに合わせて、次のような感じで書きましょう。
> assertThat(expectedFile.exists(), is(true));

こちらに対応できていません。

2023-03-06 05:37 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    @Test(expected = IllegalStateException.class)
既存のFileLogWriterTest#testInvalidFilePath、testInvalidEncodingも同じ形にしてください。

2023-03-06 06:17 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        assertTrue(appLog.contains("CURRENT FILE SIZE   = [0]"));
MockのRotatePolicyを作ってテスト時の挙動を制御してください。
今のようにFileSizeRotatePolicyに依存したテストにしてしまうと、FileSizeRotatePolicyのgetSettingsが変更された時、FileLogWriterに変更が入っていないのにテストに失敗してしまいます。

2023-03-06 06:17 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        assertTrue(appLog.contains("CURRENT FILE SIZE   = [1]"));
testInitializedMessage2のテストはFileSizeRotatePolicyの挙動をテストしているので、このクラスからは削除してください。

2023-03-06 06:17 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        };
> needsRotateでfalseが返されるので、rotateは呼ばれないです。

それをテストできちんと確認しましょうという指摘です。
[余計なメソッドが実行されていないことをチェックしたい場合は FullVerifications を使う](https://qiita.com/opengl-8080/items/a49d4dae9067413ccdd6#%E4%BD%99%E8%A8%88%E3%81%AA%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%8C%E5%AE%9F%E8%A1%8C%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%81%AA%E3%81%84%E3%81%93%E3%81%A8%E3%82%92%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%81%97%E3%81%9F%E3%81%84%E5%A0%B4%E5%90%88%E3%81%AF-fullverifications-%E3%82%92%E4%BD%BF%E3%81%86)

2023-03-06 06:18 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        }
> アサーションは、他が Hamcrest の API を使っているのに合わせて、次のような感じで書きましょう。
> assertThat(expectedFile.exists(), is(true));

2023-03-06 06:32 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +     *  maxFileSizeが20バイトだが、currentFileSizeが15バイトでmsgLengthが10バイト */
000をつけるのは読みにくいです。

> maxFileSize 20000byte = currentFileSize 19000byte + msgLength 1000byte のためrotate不要

だったら

> maxFileSize 20KB の設定に対して currentFileSize 19KB + msgLength 1KB+1byte のためrotate要

とか

> maxFileSize 20KB の設定に対して currentFileSize 20KB + msgLength 1byte のためrotate要

とかの方が説明としてわかりやすくないですか？
あと例にあげたtestNeedsRotateIfNeededの説明、要不要が逆転してますね。

2023-03-06 06:41 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        String str = getAlphaNumericString(10 * 1000);
一部だけを変えるのは余計に混乱します。
クラスのJavadocの最初にFileLogWriterが1000byteを1KBと計算しているため、このクラスでは1000byte=1KBとするという説明を書くか、FileLogWriterの仕様を1024byte=1KBと変えるかの2択だと思います。後方互換性の問題があるので今回は前者でいきましょう。

2023-03-06 06:44 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +     *  maxFileSizeが20バイトだが、currentFileSizeが15バイトでmsgLengthが10バイト */
ローテート要のものまでローテート不要と書いています。

2023-03-06 06:49 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        oldFileDateFormat.parse(oldDate);
try-catchで囲んだほうがわかりやすいと思いました。
```java
        try {
            oldFileDateFormat.parse(oldDate);
        } catch (Exception e) {
            fail("パースできる形式で日付が出力されていない");
        }
```

2023-03-06 07:18 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        }
elseで書くより最初にformattedUpdateTimeをif文の外で"00:00:00"で初期化した方がシンプルだと思います。SimpleDateFormat#parseのtry-catchもif文の外に出せるのでネストが減りますし。

2023-03-06 07:18 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        }
Calendarをインスタンス変数で引き回すのはわかりにくいのでDateにした方がいいと思います。
あとupdateCalendarという名前も名前から何が入っているかを想定できないのでnextUpdateTimeとか時刻というのがわかる名前にしましょう。

2023-03-06 07:18 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private String updateTime;
これをインスタンス変数にしているのはgetSettingsで使いたいからでしょうか？
getSettingsはパース後のDateをフォーマットしてやるようにすれば、この変数は不要ではないですか？

2023-03-06 07:18 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private String updateTime;
同じ意味の値、導出できる値を二重に持つのはやめたほうがいいです。

2023-03-06 07:18 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        // 時・分・秒・ミリ秒を0にする
時刻を設定できるようにしたことで処理とコメントが乖離してます。

2023-03-06 07:18 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        if (currentDate.after(nextUpdateCalender.getTime())) {
afterメソッドはわかりにくいのでDate#getTime()して不等号で比較するようにしましょう。

2023-03-06 07:18 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        return currentDate.after(nextUpdateDate) || currentDate.equals(nextUpdateDate);
ここもafter、equals使わず
`return currentDate.getTime() >= nextUpdateDate.getTime();`にしましょう。

2023-03-06 07:18 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        String rotatedFilePath = logFilePath  + "." + new SimpleDateFormat(datePattern).format(nextUpdateDate) + ".old";
変数宣言するならSimpleDateFormatかなと思いました。
```java
        SimpleDateFormat suffixDatePattern = new SimpleDateFormat("yyyyMMddHHmmss");
        String rotatedFilePath = logFilePath + "." + suffixDatePattern.format(nextUpdateDate) + ".old";
```

2023-03-06 07:18 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> + *     このオプションは、rotatePolicyに{@link FileSizeRotatePolicy}が設定されているか、何も設定されていない場合に有効である。</dd>
DateRotatePolicyも同様なので「下記プロパティは、rotatePolicyに{@link DateRotatePolicy}が設定されている場合に有効である。」は削除してください。

2023-03-06 08:34 UTC, kumagoro1202 requested changes
口頭で伝えた通り、FileLogWriterTestの中でFileSizeRotatePolicyの動きに依存したテストになっているものは、以下のどちらかの対応をしてください。
- FileSizeRotatePolicyの動きを確認する観点のテストは削除(FileSizeRotatePolicyの単体テストで確認する)
- FileLogWriterの動きを確認する観点だが、結果的にFileSizeRotatePolicyがデフォルトで動いていてFileSizeRotatePolicyに依存してしまっているものはモックのRotatePolicyを作成して差し替える

2023-03-06 08:34 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        DateFormat settingDateFormat = new SimpleDateFormat(settingDatePattern);
settingDatePatternを一度変数に入れる意味は無いのでSimpleDateFormatのコンストラクタ引数に直接渡せばいいと思います。

2023-03-06 08:34 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +
FileLogWriterのKBの可視性を変えてそちらを参照するようにしてください。
もしもFileLogWriterが1024byteで計算する修正が入った場合にここだけ取り残される可能性があります。
FileLogWriterに合わせて1000にしているなら、それがコードからもわかるようにしましょう。

2023-03-06 08:34 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    private static class FixedDateRotatePolicy extends DateRotatePolicy {
このクラスはどこかで再利用されるものではなく、このテストのためだけのクラスです。
なので、FixedDateRotatePolicyというクラスの動きがわかるような名前より、DateRotatePolicyForTestのように何のためのクラスというのがわかる名前の方がいいです。

2023-03-06 08:34 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    private String logFilePath = "./log/date-rotate-app.log";
この2つはfinal宣言した方がいいです。finalにすることで再代入されないことが担保されるので使う時に必ずここで宣言した値であることが保証されます。テストを読む時に再代入されていないか気をつける必要がなくなり読みやすくなります。

2023-03-06 08:34 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +            logFile.delete();
ファイル削除に失敗したらテストを失敗させるべきだと思います。

2023-03-06 08:34 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss:SSS");
一般論としてミリ秒の区切りはピリオドだと思います。
`yyyy-MM-dd hh:mm:ss.SSS`

2023-03-06 08:34 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        logFile.setLastModified(textToDate("2017-12-31 10:10:10:000").getTime());
モック化しているのでこの設定は不要だと思います。

2023-03-06 08:34 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        final DateRotatePolicy policy = new FixedDateRotatePolicy(textToDate("2018-01-01 10:10:10:000"));
ここのDateRotatePolicyはFixedDateRotatePolicyではなく元のDateRotatePolicyでいいんじゃないでしょうか？

2023-03-06 08:34 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        ((FixedDateRotatePolicy)policy).setCurrentDate(textToDate("2018-01-02 00:00:00:000"));
宣言時に`FixedDateRotatePolicy policy = new FixedDateRotatePolicy(textToDate("2018-01-01 10:10:10:000"));`としておけばキャスト不要だと思います。

2023-03-06 08:34 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +
今のテストだとnextUpdateDateがinitializeとrotateどちらも同じ値で代入されるので、rotateで更新されたということがわかりにくいです。rotateの前にcurrentDateを1/2に更新してrotate後は1/3がnextUpdateDateになるようにしましょう。

2023-03-06 08:34 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +            logFile.delete();
DateRotatePolicyTestの指摘同様、削除に失敗したらテストを失敗させるべきだと思います。

2023-03-07 01:45 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * </dl>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/4f3935c22f2d7bea557f700a91219105dc1a3c54)で修正しております。

2023-03-07 01:46 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> + *     このオプションは、rotatePolicyに{@link FileSizeRotatePolicy}が設定されているか、何も設定されていない場合に有効である。</dd>
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/ad7bfb0c3aebc33903378be56454cc21a612013c)で修正しております。

2023-03-07 01:47 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        f.createNewFile();
見落としておりました。
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/8b8d4b764b0b2863d8e116748b514fde40eb8296)で修正しております。

2023-03-07 01:48 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
失礼しました。
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/7a67ee559a45c333ff4e85b0a72aa25c9c7d4e58)で修正しております。

2023-03-07 01:49 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    @Test(expected = IllegalStateException.class)
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/cbe7ac8984caa8641d18fa37871d78e1e7f3ac90)で修正しました。

2023-03-07 01:50 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        };
レビューを読み間違えていました。
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/2961cbe48e4679209cbc8671a723f750da1df22b)で修正しております。

2023-03-07 01:50 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1122700911)のレビュー指摘対応で修正済みです。

2023-03-07 01:52 UTC, tacitusxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +     *  maxFileSizeが20バイトだが、currentFileSizeが15バイトでmsgLengthが10バイト */
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/3fa680fe8ac99f2254b54ae1a45de63d3a09762f)で修正しました。

2023-03-07 01:52 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        String str = getAlphaNumericString(10 * 1000);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/b90c93d728e6c6576f7620d977043421409b181c)で100KB=1KBとする説明を追加しました。

2023-03-07 01:53 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        oldFileDateFormat.parse(oldDate);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/18d88ee393b2326a26e4e59854685b5c58f11be5)で修正しました。

2023-03-07 01:54 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        assertTrue(appLog.contains("CURRENT FILE SIZE   = [0]"));
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/8fd4a904e6c827b6222f38c5058035ecc8ff0a3d)でFileSizeRotatePolicyの依存性をなくしました。

2023-03-07 01:54 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        assertTrue(appLog.contains("CURRENT FILE SIZE   = [1]"));
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/045226f77397ee28d92c824cef8d9bd949e12aa7)でtestInitializedMessage2のテストを削除しました。

2023-03-07 01:56 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        // 時・分・秒・ミリ秒を0にする
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/f41dc0cfcdeddb55e224a2e7c5f07dd8b8637081)でコメントを修正しております。

2023-03-07 01:57 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        return currentDate.after(nextUpdateDate) || currentDate.equals(nextUpdateDate);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/49dafe7a801bebc2ec19bab8e613229ab28417e6)で修正しております。

2023-03-07 01:57 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/acbe9fc1a5a0d2dd7a43f3be20515cf1873f87ba)で修正しております。

2023-03-07 02:08 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
ファイルの削除処理として、便利のUtilがあったので使用するように[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/05252f657f28796b493418e87b4faa46fbd815bc)で修正しました。

2023-03-07 02:10 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +     *  maxFileSizeが20バイトだが、currentFileSizeが15バイトでmsgLengthが10バイト */
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1122843229)のレビュー指摘対応で修正済みです。

2023-03-07 02:14 UTC, tacitusxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        }
たしかにそちらの方がシンプルですね。[ここ](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/83c0dc9c6b1018740f4b99cab4e601a5dbd77302)で反映しました。

2023-03-07 02:16 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        if (currentDate.after(nextUpdateCalender.getTime())) {
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/2e4d98cc500854ab10dba050c52328c6219979a1)で修正しております。

2023-03-07 02:20 UTC, tacitusxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    private String logFilePath = "./log/date-rotate-app.log";
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/1f91d0152b354d3708f59eddb40ee699c17f4086)で追記しています。

2023-03-07 03:58 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/48a3d05d21ef0a8aeb0f826747fd9e0a62acc176)で修正しました。

2023-03-07 03:58 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        ((FixedDateRotatePolicy)policy).setCurrentDate(textToDate("2018-01-02 00:00:00:000"));
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/539b3641550e382cd5bf740eed2760ff7439b02a)で修正しました。

2023-03-07 03:59 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss:SSS");
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/4fb95b70e022f6e3e199f27ac39276c4bc62a7fc)で修正しました。

2023-03-07 04:00 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +            logFile.delete();
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1122687855)のレビュー指摘対応でログファイルの削除は共通のUtilクラスを使用するようにしてしまいました。
こちらのUtilクラス自体が、logフォルダにあるファイルを全て削除するような処理のため
除に失敗したらテストを失敗するような処理を組み込むと、ログファイル書き込み中のファイルなどを削除しようとした際にテスト失敗してしまいます。

2023-03-07 04:03 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        logFile.setLastModified(textToDate("2017-12-31 10:10:10:000").getTime());
本メソッド内ではモック化されないです。

2023-03-07 04:05 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        final DateRotatePolicy policy = new FixedDateRotatePolicy(textToDate("2018-01-01 10:10:10:000"));
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/a344bf3701d61c12a604c1eb71671e8873083571)で修正しております。

2023-03-07 04:05 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +            logFile.delete();
https://github.com/nablarch/nablarch-core-applog/pull/17#discussion_r1122687855のレビュー指摘対応でログファイルの削除は共通のUtilクラスを使用するようにしてしまいました。
こちらのUtilクラス自体が、logフォルダにあるファイルを全て削除するような処理のため
削除に失敗したらテストを失敗するような処理を組み込むと、ログファイル書き込み中のファイルなどを削除しようとした際にテスト失敗してしまいます。

2023-03-07 04:07 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    private static class FixedDateRotatePolicy extends DateRotatePolicy {
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/8abb30d36e19bf901337b0c107ccfafe40ffb258)でテストモッククラスの命名を修正しました。

2023-03-07 04:07 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        DateFormat settingDateFormat = new SimpleDateFormat(settingDatePattern);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/176c98b5a73a3cc4e3fa7fa2f9c441b9fe6cb52a)で修正しております。

2023-03-07 04:08 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        String rotatedFilePath = logFilePath  + "." + new SimpleDateFormat(datePattern).format(nextUpdateDate) + ".old";
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/176c98b5a73a3cc4e3fa7fa2f9c441b9fe6cb52a)で宣言しないように修正しました。

2023-03-07 04:09 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        }
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/e1e36d5444aa98f61bb43acb677a7b0694934633)で修正しております。

2023-03-07 04:09 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private String updateTime;
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/e1e36d5444aa98f61bb43acb677a7b0694934633)で修正しております。

2023-03-07 04:11 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        assertTrue(appLog.contains("CURRENT FILE SIZE   = [0]"));
testNotSwitchedのテストも、FileLogWriterのテストとして不要だと判断したため削除しています。

2023-03-07 04:37 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    private static class FixedDateRotatePolicy extends DateRotatePolicy {
呼び出し元の変更漏れがあり[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/f2b65a6a6afba0320beb3a4d37b6d261a4304388)で修正しております。

2023-03-07 04:53 UTC, takikunxo commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +    private String updateTime;
上のレビュー指摘で添付したコミットと同じです。

2023-03-07 05:07 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    @Test(expected = IllegalStateException.class)
他と合わせて`CoreMatchers.is`はstaticインポートしてください。その方が自然な英語に近くなって読みやすくなります。

2023-03-07 05:22 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        };
rotateが呼び出されないことのチェックだけじゃなく、他の部分のRotatePolicy呼び出しも想定外のメソッドが呼び出されていないことは確認しましょう。

2023-03-07 05:30 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        oldFileDateFormat.parse(oldDate);
catch節が改行されていると独立したブロックのように見えて違和感があるので、上で書いたスニペットのように改行しないようにしてもらえますか。

2023-03-07 05:34 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        }
```java
        String formattedUpdateTime;
        if (updateTime == null) {
            formattedUpdateTime = "00:00:00";
        } else {
```
ここのif-elseも不要です。
```java
        String formattedUpdateTime = "00:00:00";
        if (updateTime != null) {
```
としたほうがスッキリします。

2023-03-07 05:39 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        }
`Date#getHours()`、`getMinutes()`、`getSeconds()`は`Deprecated`なのでCalendarを使ってください。
```java
    private Date calcNextUpdateDate(Date currentDate) {
        Calendar nextUpdateCalender = Calendar.getInstance();
        nextUpdateCalender.setTime(currentDate);
        Calendar nextUpdateTimeCalendar = Calendar.getInstance();
        nextUpdateTimeCalendar.setTime(nextUpdateTime);
        
        // 時・分・秒としてupdateTimeに指定された値を設定する
        nextUpdateCalender.set(Calendar.HOUR_OF_DAY, nextUpdateTimeCalendar.get(Calendar.HOUR_OF_DAY));
```

2023-03-07 05:40 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        }
あとnextUpdateCalenderはtypoしてますね。Calendarの最後のaがeになってる。

2023-03-07 05:50 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +        if (currentDate.after(nextUpdateCalender.getTime())) {
`getTime().getTime()`と続くのは気持ち悪いので一旦変数に入れましょう。
```java
        // 現在時刻の時分秒 > nextUpdateTimeの時分秒の場合は、日付に1を加える
        Date nextUpdateDate = nextUpdateCalender.getTime();
        if (currentDate.getTime() > nextUpdateDate.getTime()) {
            nextUpdateCalender.add(Calendar.DATE, 1);
        }

        return nextUpdateDate;
```

2023-03-07 06:07 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        logFile.setLastModified(textToDate("2017-12-31 10:10:10:000").getTime());
モック化されています。

2023-03-07 06:09 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        ((FixedDateRotatePolicy)policy).setCurrentDate(textToDate("2018-01-02 00:00:00:000"));
testNeedsRotateIfNoNeededやtestNeedsRotateIfCurrentDateEqualsNextUpdateDateなど他のキャストしている個所も同様に宣言する型をDateRotatePolicyForTestにしましょう。

2023-03-07 06:12 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +
> rotateは2018年1月2日のため、次回更新時刻は2018年の1月3日になっている

これは

> 現在日時は2018年1月2日のため、次回更新時刻は2018年1月3日になる

こういう意味？「rotateは◯月◯日」は違和感があります。

2023-03-07 08:15 UTC, kumagoro1202 requested changes

2023-03-07 08:15 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +     */
もう少し詳しく仕様を書いて欲しい。updateTimeが設定されている場合とされていない場合それぞれどのような計算がされるのか。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> +     */
次回ローテーション時刻を更新していることも記載しましょう。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +     * {@link FileSizeRotatePolicy}では、読み込んだファイルサイズを現在のファイルサイズとして、インスタンス変数に保持する。
自身のJavadocにおいて`{@link FileSizeRotatePolicy}では、`は冗長なので不要です。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/FileSizeRotatePolicy.java
> +     * {@link FileSizeRotatePolicy}では、ファイルサイズに書き込むメッセージサイズを足すことで、現在のファイルサイズを更新する。
自身のJavadocにおいて{@link FileSizeRotatePolicy}では、は冗長なので不要です。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        boolean actual = policy.needsRotate("abcdeabcde",
abcdeabcdeを何度もリテラルで書くより、Charsetなど同様`private final String message = "dummy-message";`のように宣言して使いまわしましょう。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        final DateRotatePolicy policy = new FixedDateRotatePolicy(textToDate("2018-01-01 10:10:10:000"));
修正対象が違います。testNeedsIfFileExistsを修正していますが、指摘はtestLastModifiedReturnsZeroです。
testNeedsIfFileExistsはcurrentDateを制御しないと(あり得ないですが)2017-12-31より前の日にテスト実行すると失敗します。
testLastModifiedReturnsZeroではcurrentDateを使われることがないので、固定値にする必要がなく元のDateRotatePolicyでいいんじゃないかという指摘です。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        File logFile = new File(logFilePath);
`new File(logFilePath)`を変数にするべきです。

```java
        File logFile = new File(logFilePath);
        logFile.createNewFile();
        
        // ロテート前
        // リネーム前のファイルが存在すること
        assertThat(logFile.exists(), is(true));

        // リネーム後のファイルが存在しないこと
        String expectedPath = "./log/testRotate-app.log.old";
        File expectedFile = new File(expectedPath);
        assertThat(expectedFile.exists(), is(false));
```

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    };
updateTimeが設定されていない場合のテストを追加してください。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +        }
計算するよりexpectedなupdateTimeとしてDateFixtureに持たせた方が読みやすいと思います。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +                + "\tCURRENT DATE        = ["+settingDateFormat.format(textToDate(dateFixture.currentDate)) +"]" + Logger.LS
ミリ秒つかってないのでDateFixtureに持たせるcurrentDateは秒までにすればいいと思います。
```java
        DateRotatePolicy policy = new DateRotatePolicyForTest(textToDate(dateFixture.currentDate));

        String settingDatePattern = "yyyy-MM-dd HH:mm:ss";
        DateFormat settingDateFormat = new SimpleDateFormat(settingDatePattern);

                + "\tCURRENT DATE        = [" + settingDateFormat.format(textToDate(dateFixture.currentDate)) + "]" + Logger.LS
```
が
```java
        DateRotatePolicy policy = new DateRotatePolicyForTest(textToDate(dateFixture.currentDate + ".000"));

                + "\tCURRENT DATE        = [" + dateFixture.currentDate + "]" + Logger.LS
```
になって見通しがよくなると思います。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        assertTrue(appLog.contains("ROTATE POLICY CLASS = [nablarch.core.log.basic.RotatePolicyForTest]"));
これだとRotatePolicyがgetSettingでnullを返したから何も出ていないのか、FileLogWiterの実装ミスってRotatePolicyのgetSetting使わないようになってるのかの区別がつかないので、RotatePolicyForTestのgetSettingで何かしら返すようにしてください。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        settings.put("appFile.rotatePolicy", "nablarch.core.log.basic.RotatePolicyForTest");
testSwitchedというテスト全体に対しての指摘です。
初見でこのテスト何をしたいのかがまったくわからないです。
そもそもRotatePolicyのneedsRotateやrotateが呼ばれていることがテストできていれば、実際にファイルがローテーションされるかどうかはFileLogWiterの責務ではないです。このテストは不要だと思います。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +    public void testSwitchedUnderInfoLevel() {
このテストもfor文まわして何回かに一回ローテーションされるような挙動にしなくても、必ずローテーションするRotatePolicyを作成して一回writeすればいいと思います。テストを読み解くのが大変で何をテストしたいのかがわからないです。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        settings.put("appFile.rotatePolicy", "nablarch.core.log.basic.RotatePolicyForTest");
このテストのJavadoc途中でJavadocの終了コードが来ていておかしなことになっています。

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        // currentFileSizeに5KBを加えて、19KBに設定
19KB→20KB

2023-03-07 08:15 UTC, kumagoro1202 commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        assertThat(policy.needsRotate(generateZeroPaddingString(10 * 1000), Charset.defaultCharset()), is(false));
ここだけ1000とハードコーディングしてしまっている。

2023-03-07 11:16 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/DateRotatePolicyTest.java
> +    @Test(expected = IllegalStateException.class)
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/30d6a74d6678a0805d80e32ac2c9477654d3174a)で修正しました。

2023-03-07 11:16 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileLogWriterTest.java
> +        };
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/2a1c03f84cc25618d3e86d2c6b926e06d10e894b)で修正しました。

2023-03-07 11:17 UTC, takikunxo commented on src/test/java/nablarch/core/log/basic/FileSizeRotatePolicyTest.java
> +        oldFileDateFormat.parse(oldDate);
[こちら](https://github.com/nablarch/nablarch-core-applog/pull/17/commits/40089e008a918b46782e0c25bf86fb6c0a3edc05)で修正しました。

2023-03-08 06:17 UTC, opengl-8080 requested changes

2023-03-08 06:17 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * ログ書き込み時の現在時刻 >= インスタンス変数として保持している次回ローテション時刻の場合、ローテーションを行う。<br>
> インスタンス変数として保持している次回ローテション時刻

ここでは仕様の説明に集中したほうがいいと思うので、「インスタンス変数として保持している」は実装の詳細に見込んでいてノイズになるのでない方が良いと思いました。

2023-03-08 06:17 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * </ol>
分かりにくいと思いました。

> ログファイルの最終更新日時を現在日時として扱う

「現在日時」には現在の日時という意味があるので、「最終更新日時を現在日時として扱う」というのは表現が分かりにくいと思いました。
何かしら別の名前、例えば「基準日時」などと定義するのはどうでしょう。

また「1.で算出した日時」というのも、都度 1 の定義を見直さないとどれのことかパッと理解できないので分かりにくいと思いました。
「現在日時の時刻部分をupdateTimeに設定されている時刻とする」というのも、ぱっと見何を言っているのか分かりにくいと感じました。
やりたいのは時刻の比較だけなので、無理に時刻を置き換えた別の日時を用意しなくてもいいのではないかなと思いました。

↓のような説明でどうでしょう？

> システム起動時の次回ローテーション日時は、以下の通り算出する。
> 
> まず、次回ローテーション日時を決める元となる基準日時を決定する。
> 基準日時は、ログファイルが既に存在するかどうかで以下のように決定する。
> 存在する場合→ログファイルの最終更新日時
> 存在しない場合→システム日時
> 
> 次に、基準日時の時刻と updateTime の時刻を比較して、次回ローテーション日時の日付を決定する。
> 基準日時の時刻 <= updateTime → システム日付
> updateTime < 基準日時の時刻 → システム日付 + 1日
> 
> この日付に updateTime の時刻を設定したものを、システム起動時の次回ローテーション日時とする。
> 
> システム起動時以外の次回ローテーション日時は、直近の次回ローテーション日時の日付を1日加算したものを使用する。

あと、この手の説明は具体例がないと読んで解釈した内容が本当に正しいか判断ができないので、具体例も載せた方がいいと思いました。
（上の例は具体例は省略しています）

---

その他、気になったポイント。

- `<ol>` タグを使っていますが、各説明が順序になっていないと思いました（特に２と３は分岐になっていて順序ではない）
- 「次回ローテーション時刻」ではなく「次回ローテーション日時」ではないでしょうか
  - 「現在日時の時刻部分」という表現から、「時刻」は時分秒のみの時間という意味で使っているので
  - 他にも日時の意味で時刻を使っているところがあるので、表現を統一したほうがいいかと思いました
- 次回ローテーション日時自体はローテーションするたびに更新されているはずですが、元の説明だとそのことが書かれておらず、またシステム起動時のケースしか書かれていないのが良くないと思いました

2023-03-08 06:17 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * この時、yyyyMMddHHmmssSSSにはローテーション実施時刻が出力される。
この説明だけ見ると、最初からローテーション実施時刻でミリ秒まで出してローテーションすればいいのではないかと思いました。
（同名ファイルのチェックも不要）

もともとは業務日付もあって日付単位のローテーションを前提としていたとき、ファイル名が重複したらどうしようという話でこのチェックをするようになったと記憶しています。
しかし、業務日付でのローテーションがなくなって、秒単位でのローテーションまでサポートするようになった今となっては要らなくなった仕様に感じました。

2023-03-08 17:35 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * </ol>
修正しました。
https://github.com/nablarch/nablarch-core-applog/pull/17/commits/db355eaddd94b02e70c6fb5b91bbb77657f720ac

あわせて更新、ローテーション、CHANGE、update、rotateなど、ローテーションをバラバラの表記していたのを統一しました。
https://github.com/nablarch/nablarch-core-applog/pull/17/commits/8674bf50850dd63892e7b091da45eaa961d31e51

2023-03-08 17:35 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * この時、yyyyMMddHHmmssSSSにはローテーション実施時刻が出力される。
たしかにそうですね。修正しました。
https://github.com/nablarch/nablarch-core-applog/pull/17/commits/7b6a98d7c7e40861d0e62d5716e2412427946260

2023-03-08 17:36 UTC, kumagoro1202 commented
追加で、ログ出力していたrotateTimeですが、nextRotateDateTimeの出力を見れば設定はわかるので削除しました。
https://github.com/nablarch/nablarch-core-applog/pull/17/commits/3f92c5a25ad978dd472fd80774326b8cb46dd221

2023-03-08 17:37 UTC, kumagoro1202 commented
指摘あげて修正するほどでもないけど個人的に気になっていた個所合わせて修正しました。
https://github.com/nablarch/nablarch-core-applog/pull/17/commits/dddd098efe0228ac57f9526990d5790e5765ffad

2023-03-09 00:44 UTC, opengl-8080 commented
> 追加で、ログ出力していたrotateTimeですが、nextRotateDateTimeの出力を見れば設定はわかるので削除しました。

ちゃんと設定されているか確認するためのログなので、設定値は出しておいた方がいいのではないでしょうか？

2023-03-09 00:48 UTC, opengl-8080 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * </ol>
html で見たときに、文章が隙間なく並んでいて読みづらく感じました。
`<p>` タグを使うなどして、適宜段落分けをした方がいいのではないかと思いました。

2023-03-09 01:32 UTC, kumagoro1202 commented on src/main/java/nablarch/core/log/basic/DateRotatePolicy.java
> + * </ol>
整形しました。
https://github.com/nablarch/nablarch-core-applog/pull/17/commits/ddc9cc271002e90dffd353bce106feec5c1ca5e7

2023-03-09 01:34 UTC, kumagoro1202 commented
> > 追加で、ログ出力していたrotateTimeですが、nextRotateDateTimeの出力を見れば設定はわかるので削除しました。
> 
> ちゃんと設定されているか確認するためのログなので、設定値は出しておいた方がいいのではないでしょうか？

ちゃんと設定されているかはnextRotateDateTimeの時刻を見ればわかると思いました。rotateTimeを設定したのにnextRotateDateTimeの時刻が00:00:00なら設定が効いてないことがわかるかと。
ただ、どこまで設定が届いているかを判定するために出しておいた方が良い気もしてきたので、出すように修正しました。
元の並び順には違和感があったので、設定値→次回ローテーション日時→現在日時の順に並べ替えています。
https://github.com/nablarch/nablarch-core-applog/pull/17/commits/f07da73d012d646b568d4738dc5aaa27b2e760bc
https://github.com/nablarch/nablarch-core-applog/pull/17/commits/7e036e7ae0a96d50ccd4daeea237261556e16067

2023-03-09 01:46 UTC, kumagoro1202 commented
developへの取り込みは #18 にて行う。

2023-03-09 01:46 UTC, closed without merging